/* =========================================================================
   English for Spa & Wellness Professionals — content data
   Every entry that a learner reads carries an English field and, where it
   is the target learning content, a Thai (`th`) field for direct support.
   ========================================================================= */

/* ---------- VOCABULARY ---------- */
const VOCAB_CATEGORIES = [
  { id:'massage',    en:'Massage & bodywork',        th:'นวดและการบำบัดร่างกาย' },
  { id:'skin',       en:'Facial & skincare',         th:'ผิวหน้าและการดูแลผิว' },
  { id:'modality',   en:'Body treatments',           th:'ทรีตเมนต์ร่างกาย' },
  { id:'beauty',     en:'Nail & beauty care',        th:'เล็บและความงาม' },
  { id:'safety',     en:'Safety & hygiene',          th:'ความปลอดภัยและสุขอนามัย' },
  { id:'care',       en:'Client care & front desk',  th:'การดูแลลูกค้าและหน้าเคาน์เตอร์' },
  { id:'facilities', en:'Spa facilities',            th:'สิ่งอำนวยความสะดวกในสปา' },
  { id:'wellness',   en:'Wellness & body',           th:'สุขภาวะและร่างกาย' },
  { id:'team',       en:'Teamwork & shift talk',     th:'การทำงานเป็นทีมและการเข้ากะ' },
];

const VOCAB = [
  // massage & bodywork (16)
  { word:'Effleurage', th:'การนวดลูบผิวเบาๆ', phon:'/ˌef.lɜːˈrɑːʒ/', cat:'massage', def:'Long, light, gliding strokes used to warm the tissue and open a massage sequence.', short:'Light, gliding opening stroke' },
  { word:'Petrissage', th:'การนวดคลึงและบีบกล้ามเนื้อ', phon:'/ˈpet.rɪ.sɑːʒ/', cat:'massage', def:'Kneading, rolling and lifting movements that work more deeply into the muscle.', short:'Kneading, deeper muscle work' },
  { word:'Acupressure', th:'การกดจุด', phon:'/ˈæk.juːˌpreʃ.ər/', cat:'massage', def:'Applying finger or thumb pressure to specific points on the body to ease tension.', short:'Finger pressure on set points' },
  { word:'Reflexology', th:'การนวดกดจุดสะท้อนฝ่าเท้า', phon:'/ˌriː.flekˈsɒl.ə.dʒi/', cat:'massage', def:'Pressure-point work on the feet, hands or ears, linked to other areas of the body.', short:'Pressure points on feet/hands' },
  { word:'Deep tissue', th:'การนวดเนื้อเยื่อส่วนลึก', phon:'/diːp ˈtɪʃ.uː/', cat:'massage', def:'A firmer massage technique that reaches the inner layers of muscle and connective tissue.', short:'Firm work on inner muscle layers' },
  { word:'Lymphatic drainage', th:'การนวดระบายน้ำเหลือง', phon:'/lɪmˈfæt.ɪk ˈdreɪ.nɪdʒ/', cat:'massage', def:'Very gentle, rhythmic strokes that encourage fluid to move through the lymph system.', short:'Gentle strokes to move fluid' },
  { word:'Tapotement', th:'การนวดสับเบาๆ', phon:'/ˈtæp.ə.tmənt/', cat:'massage', def:'Rhythmic tapping or percussion movements used to stimulate the muscles.', short:'Rhythmic tapping movement' },
  { word:'Friction', th:'การนวดคลึงเป็นวงกลม', phon:'/ˈfrɪk.ʃən/', cat:'massage', def:'Small, deep, circular movements applied to help break down muscle knots.', short:'Small deep circular movement' },
  { word:'Trigger point', th:'จุดกดเจ็บ', phon:'/ˈtrɪg.ər pɔɪnt/', cat:'massage', def:'A tight, sensitive spot in a muscle that can cause pain elsewhere in the body.', short:'A tight, sensitive muscle spot' },
  { word:'Kneading', th:'การนวดคลึงคล้ายนวดแป้ง', phon:'/ˈniː.dɪŋ/', cat:'massage', def:'Squeezing and rolling the muscle between the fingers and palm, like working dough.', short:'Squeezing and rolling muscle' },
  { word:'Compression', th:'การกดนวดเป็นจังหวะ', phon:'/kəmˈpreʃ.ən/', cat:'massage', def:'Applying firm, rhythmic pressure with the palm or fist to warm the muscle.', short:'Firm rhythmic palm pressure' },
  { word:'Assisted stretching', th:'การยืดกล้ามเนื้อโดยผู้ช่วย', phon:'/əˈsɪs.tɪd ˈstretʃ.ɪŋ/', cat:'massage', def:'Gently lengthening a guest\u2019s muscles through guided movement during a treatment.', short:'Guided muscle lengthening' },
  { word:'Range of motion', th:'ช่วงการเคลื่อนไหวของข้อต่อ', phon:'/reɪndʒ əv ˈməʊ.ʃən/', cat:'massage', def:'How far a joint can comfortably move in different directions.', short:'How far a joint can move' },
  { word:'Thai massage', th:'นวดแผนไทย', phon:'/taɪ ˈmæs.ɑːʒ/', cat:'massage', def:'A traditional treatment combining stretching, acupressure and rhythmic compression, performed on a mat.', short:'Stretching + acupressure on a mat' },
  { word:'Swedish massage', th:'นวดสวีดิช', phon:'/ˈswiː.dɪʃ ˈmæs.ɑːʒ/', cat:'massage', def:'A classic full-body massage using long strokes to relax and improve circulation.', short:'Classic long-stroke full-body massage' },
  { word:'Sports massage', th:'นวดกีฬา', phon:'/spɔːts ˈmæs.ɑːʒ/', cat:'massage', def:'A firmer massage designed to prevent injury and aid recovery for active guests.', short:'Firm massage for injury prevention' },

  // facial & skincare (16)
  { word:'Exfoliation', th:'การขัดผิว', phon:'/ˌeks.fəʊ.liˈeɪ.ʃən/', cat:'skin', def:'Removing dead skin cells from the surface, usually with a scrub or a gentle acid.', short:'Removing dead skin cells' },
  { word:'Extraction', th:'การกดสิว', phon:'/ɪkˈstræk.ʃən/', cat:'skin', def:'Manually clearing a blocked pore, most often carried out during a facial.', short:'Manually clearing a pore' },
  { word:'Microdermabrasion', th:'การขัดผิวหน้าด้วยเครื่องไมโครเดิร์ม', phon:'/ˌmaɪ.krəʊˌdɜː.məˈbreɪ.ʒən/', cat:'skin', def:'A machine-based treatment that gently resurfaces the outermost layer of skin.', short:'Machine skin resurfacing' },
  { word:'Blemish', th:'ตำหนิบนผิว', phon:'/ˈblem.ɪʃ/', cat:'skin', def:'A small mark or imperfection on the skin, such as a spot or patch of redness.', short:'A small skin imperfection' },
  { word:'Hydrating', th:'ให้ความชุ่มชื้น', phon:'/ˈhaɪ.dreɪ.tɪŋ/', cat:'skin', def:'Describes a treatment or product that restores moisture to dry or tired-looking skin.', short:'Restores moisture to the skin' },
  { word:'Cleansing', th:'การทำความสะอาดผิว', phon:'/ˈklen.zɪŋ/', cat:'skin', def:'The first step of a facial, removing dirt, oil and make-up from the skin.', short:'First step of a facial' },
  { word:'Toning', th:'การปรับสภาพผิวด้วยโทนเนอร์', phon:'/ˈtəʊ.nɪŋ/', cat:'skin', def:'Applying a light liquid to balance the skin\u2019s pH after cleansing.', short:'Balances skin after cleansing' },
  { word:'Serum', th:'เซรั่ม', phon:'/ˈsɪə.rəm/', cat:'skin', def:'A concentrated liquid treatment applied before moisturiser to target specific skin concerns.', short:'Concentrated targeted treatment' },
  { word:'Moisturiser', th:'มอยส์เจอไรเซอร์', phon:'/ˈmɔɪs.tʃər.aɪ.zər/', cat:'skin', def:'A cream or lotion applied to seal in hydration and protect the skin.', short:'Seals in hydration' },
  { word:'Sunscreen', th:'ครีมกันแดด', phon:'/ˈsʌn.skriːn/', cat:'skin', def:'A product that protects the skin from harmful UV rays.', short:'Protects skin from UV rays' },
  { word:'Collagen', th:'คอลลาเจน', phon:'/ˈkɒl.ə.dʒən/', cat:'skin', def:'A natural protein in the skin that keeps it firm and elastic.', short:'Protein that keeps skin firm' },
  { word:'Pore', th:'รูขุมขน', phon:'/pɔːr/', cat:'skin', def:'A tiny opening in the skin through which oil and sweat are released.', short:'A tiny opening in the skin' },
  { word:'Combination skin', th:'ผิวผสม', phon:'/ˌkɒm.bɪˈneɪ.ʃən skɪn/', cat:'skin', def:'A skin type that is oily in some areas, like the T-zone, and dry in others.', short:'Oily and dry areas together' },
  { word:'Breakout', th:'สิวขึ้น', phon:'/ˈbreɪk.aʊt/', cat:'skin', def:'A sudden appearance of spots or pimples on the skin.', short:'Sudden appearance of spots' },
  { word:'Chemical peel', th:'การลอกผิวด้วยกรด', phon:'/ˈkem.ɪ.kəl piːl/', cat:'skin', def:'A treatment using a mild acid solution to remove the outer layer of skin.', short:'Mild acid resurfacing' },
  { word:'Anti-ageing', th:'ต้านริ้วรอย', phon:'/ˌæn.tiˈeɪ.dʒɪŋ/', cat:'skin', def:'Describes products or treatments designed to reduce the visible signs of ageing.', short:'Reduces visible signs of ageing' },

  // body treatments & modalities (14)
  { word:'Hydrotherapy', th:'ธาราบำบัด', phon:'/ˌhaɪ.drəʊˈθer.ə.pi/', cat:'modality', def:'Using water — jets, baths or steam — for a therapeutic and relaxing effect.', short:'Water-based treatment' },
  { word:'Aromatherapy', th:'สุคนธบำบัด', phon:'/əˌrəʊ.məˈθer.ə.pi/', cat:'modality', def:'Using essential oils extracted from plants to support wellbeing during a treatment.', short:'Treatment using essential oils' },
  { word:'Thermotherapy', th:'การบำบัดด้วยความร้อน', phon:'/ˌθɜː.məʊˈθer.ə.pi/', cat:'modality', def:'Using heat — such as hot stones or warm wraps — to help muscles relax.', short:'Using heat to relax muscles' },
  { word:'Body wrap', th:'การพอกตัว', phon:'/ˈbɒd.i ræp/', cat:'modality', def:'A treatment in which the body is covered in a product, then wrapped to intensify its effect.', short:'Product applied, then wrapped' },
  { word:'Rejuvenating', th:'ฟื้นฟูความอ่อนเยาว์', phon:'/rɪˈdʒuː.və.neɪ.tɪŋ/', cat:'modality', def:'Making the skin, or the whole guest, look and feel fresher and more energised.', short:'Makes skin look fresher' },
  { word:'Cryotherapy', th:'การบำบัดด้วยความเย็น', phon:'/ˌkraɪ.əʊˈθer.ə.pi/', cat:'modality', def:'A treatment using very cold temperatures to reduce inflammation and refresh the body.', short:'Cold treatment, reduces swelling' },
  { word:'Sauna', th:'ห้องซาวน่า', phon:'/ˈsɔː.nə/', cat:'modality', def:'A small room heated to a high temperature, used to promote sweating and relaxation.', short:'A hot, dry heated room' },
  { word:'Steam room', th:'ห้องอบไอน้ำ', phon:'/stiːm ruːm/', cat:'modality', def:'A heated room filled with moist steam, used to cleanse and relax the body.', short:'A hot, moist heated room' },
  { word:'Detoxifying', th:'ล้างพิษ', phon:'/diːˈtɒk.sɪ.faɪ.ɪŋ/', cat:'modality', def:'Describes a treatment believed to help remove unwanted toxins from the body.', short:'Helps remove toxins' },
  { word:'Salt scrub', th:'การขัดผิวด้วยเกลือ', phon:'/sɒlt skrʌb/', cat:'modality', def:'An exfoliating treatment using coarse salt mixed with oil.', short:'Coarse salt exfoliating treatment' },
  { word:'Mud treatment', th:'การพอกโคลน', phon:'/mʌd ˈtriːt.mənt/', cat:'modality', def:'A body treatment using natural mineral-rich mud to nourish and detoxify the skin.', short:'Mineral-rich mud treatment' },
  { word:'Balinese massage', th:'นวดบาหลี', phon:'/ˌbæl.ɪˈniːz ˈmæs.ɑːʒ/', cat:'modality', def:'An Indonesian-style massage combining stretching, acupressure and aromatherapy oils.', short:'Indonesian stretch + oil massage' },
  { word:'Hot stone therapy', th:'นวดหินร้อน', phon:'/hɒt stəʊn ˈθer.ə.pi/', cat:'modality', def:'A massage using smooth, heated stones to relax muscles deeply.', short:'Massage with heated stones' },
  { word:'Herbal compress', th:'ประคบสมุนไพร', phon:'/ˈhɜː.bəl ˈkɒm.pres/', cat:'modality', def:'A warm bundle of steamed herbs pressed onto the body to ease tension.', short:'Warm steamed herb bundle' },

  // nail & beauty care (10)
  { word:'Manicure', th:'การทำเล็บมือ', phon:'/ˈmæn.ɪ.kjʊər/', cat:'beauty', def:'A treatment to care for and beautify the hands and nails.', short:'Hand and nail treatment' },
  { word:'Pedicure', th:'การทำเล็บเท้า', phon:'/ˈped.ɪ.kjʊər/', cat:'beauty', def:'A treatment to care for and beautify the feet and toenails.', short:'Foot and toenail treatment' },
  { word:'Cuticle', th:'หนังกำพร้าโคนเล็บ', phon:'/ˈkjuː.tɪ.kəl/', cat:'beauty', def:'The thin layer of skin at the base of the nail.', short:'Thin skin at nail base' },
  { word:'Buffing', th:'การขัดเล็บให้เงา', phon:'/ˈbʌf.ɪŋ/', cat:'beauty', def:'Gently smoothing and polishing the surface of the nail.', short:'Smoothing and polishing nails' },
  { word:'Gel polish', th:'เจลทาเล็บ', phon:'/dʒel ˈpɒl.ɪʃ/', cat:'beauty', def:'A long-lasting nail colour that is cured under UV or LED light.', short:'Long-lasting UV-cured nail colour' },
  { word:'Waxing', th:'การแวกซ์ขน', phon:'/ˈwæk.sɪŋ/', cat:'beauty', def:'A hair removal method using warm wax to lift hair from the root.', short:'Warm-wax hair removal' },
  { word:'Threading', th:'การถอนขนด้วยด้าย', phon:'/ˈθred.ɪŋ/', cat:'beauty', def:'A precise hair removal technique using twisted cotton thread, often for eyebrows.', short:'Thread hair removal, for brows' },
  { word:'Tinting', th:'การย้อมสีขนตาหรือคิ้ว', phon:'/ˈtɪn.tɪŋ/', cat:'beauty', def:'Applying a semi-permanent dye to lashes or brows to darken them.', short:'Dyeing lashes or brows darker' },
  { word:'Callus', th:'ผิวหนังด้าน', phon:'/ˈkæl.əs/', cat:'beauty', def:'An area of thickened, hardened skin, often found on the feet.', short:'Thickened, hardened skin' },
  { word:'Ingrown nail', th:'เล็บขบ', phon:'/ˈɪn.grəʊn neɪl/', cat:'beauty', def:'A nail that has grown into the surrounding skin, sometimes causing discomfort.', short:'A nail grown into the skin' },

  // safety & hygiene (12)
  { word:'Contraindication', th:'ข้อห้ามในการทำทรีตเมนต์', phon:'/ˌkɒn.trə.ɪn.dɪˈkeɪ.ʃən/', cat:'safety', def:'A health condition or factor that means a particular treatment should not go ahead.', short:'A reason a treatment is unsafe' },
  { word:'Sanitise', th:'การฆ่าเชื้อ', phon:'/ˈsæn.ɪ.taɪz/', cat:'safety', def:'To clean tools, equipment or surfaces thoroughly to prevent the spread of infection.', short:'Clean thoroughly to prevent infection' },
  { word:'Patch test', th:'การทดสอบภูมิแพ้บนผิวหนัง', phon:'/pætʃ test/', cat:'safety', def:'A small trial application of a product, used to check for a reaction before full use.', short:'Small trial of a product' },
  { word:'Consultation form', th:'แบบฟอร์มซักประวัติ', phon:'/ˌkɒn.sʌlˈteɪ.ʃən fɔːm/', cat:'safety', def:'A written record of a guest\u2019s health history, needs and treatment preferences.', short:'Written record of guest health' },
  { word:'Sterilise', th:'การทำให้ปราศจากเชื้อ', phon:'/ˈster.ɪ.laɪz/', cat:'safety', def:'To completely destroy all bacteria and germs on tools, usually using heat.', short:'Completely destroy bacteria on tools' },
  { word:'Disposable', th:'ใช้แล้วทิ้ง', phon:'/dɪˈspəʊ.zə.bəl/', cat:'safety', def:'Designed to be thrown away after a single use, such as gloves or slippers.', short:'Designed to be thrown away' },
  { word:'Allergic reaction', th:'อาการแพ้', phon:'/əˈlɜː.dʒɪk riˈæk.ʃən/', cat:'safety', def:'An unwanted response by the body to a product or ingredient.', short:'Unwanted response to a product' },
  { word:'Pressure sensitivity', th:'ความไวต่อแรงกด', phon:'/ˈpreʃ.ər ˌsen.sɪˈtɪv.ɪ.ti/', cat:'safety', def:'How much or how little pressure a guest\u2019s body can comfortably tolerate.', short:'How much pressure a body can take' },
  { word:'Informed consent', th:'การยินยอมหลังรับทราบข้อมูล', phon:'/ɪnˈfɔːmd kənˈsent/', cat:'safety', def:'A guest\u2019s clear agreement to a treatment after understanding what it involves.', short:'Clear agreement after understanding' },
  { word:'Cross-contamination', th:'การปนเปื้อนข้าม', phon:'/krɒs kənˌtæm.ɪˈneɪ.ʃən/', cat:'safety', def:'The unwanted transfer of bacteria or products between surfaces, tools or people.', short:'Unwanted transfer of bacteria' },
  { word:'Medical history', th:'ประวัติทางการแพทย์', phon:'/ˈmed.ɪ.kəl ˈhɪs.tər.i/', cat:'safety', def:'A record of a guest\u2019s past and current health conditions.', short:'Record of past/current health' },
  { word:'First aid', th:'การปฐมพยาบาล', phon:'/fɜːst eɪd/', cat:'safety', def:'Basic emergency treatment given to someone who is injured or unwell.', short:'Basic emergency treatment' },

  // client care & front desk (14)
  { word:'Complimentary', th:'บริการฟรี', phon:'/ˌkɒm.plɪˈmen.tər.i/', cat:'care', def:'Offered free of charge, as an included part of the service or as a small gift.', short:'Offered free of charge' },
  { word:'Reschedule', th:'เลื่อนนัดหมาย', phon:'/ˌriːˈʃed.juːl/', cat:'care', def:'To move a guest\u2019s booking to a different date or time.', short:'Move a booking to another time' },
  { word:'Deposit', th:'เงินมัดจำ', phon:'/dɪˈpɒz.ɪt/', cat:'care', def:'A partial payment made in advance to secure a booking.', short:'Advance payment to secure a booking' },
  { word:'Cancellation policy', th:'นโยบายการยกเลิก', phon:'/ˌkæn.səlˈeɪ.ʃən ˈpɒl.ə.si/', cat:'care', def:'The spa\u2019s rules about cancelling or changing a booking.', short:'Rules about cancelling a booking' },
  { word:'Gift voucher', th:'บัตรกำนัล', phon:'/gɪft ˈvaʊtʃ.ər/', cat:'care', def:'A card or certificate that can be exchanged for a treatment or product.', short:'Exchangeable for a treatment' },
  { word:'Loyalty programme', th:'โปรแกรมสมาชิกสะสมแต้ม', phon:'/ˈlɔɪ.əl.ti ˈprəʊ.græm/', cat:'care', def:'A scheme that rewards returning guests with points, discounts or gifts.', short:'Rewards returning guests' },
  { word:'Waiting list', th:'รายชื่อรอคิว', phon:'/ˈweɪ.tɪŋ lɪst/', cat:'care', def:'A list of guests hoping to book a slot that is currently full.', short:'List of guests hoping for a slot' },
  { word:'Itinerary', th:'กำหนดการทรีตเมนต์', phon:'/aɪˈtɪn.ər.ər.i/', cat:'care', def:'A planned schedule of treatments or activities for a guest\u2019s visit.', short:'Planned schedule for a visit' },
  { word:'Upsell', th:'การแนะนำบริการเพิ่มเติม', phon:'/ˈʌp.sel/', cat:'care', def:'To politely suggest an additional or upgraded treatment or product.', short:'Politely suggest an upgrade' },
  { word:'Feedback form', th:'แบบฟอร์มความคิดเห็น', phon:'/ˈfiːd.bæk fɔːm/', cat:'care', def:'A short survey guests complete to share their experience.', short:'Short survey of guest experience' },
  { word:'VIP guest', th:'แขกวีไอพี', phon:'/ˌviː.aɪˈpiː gest/', cat:'care', def:'A very important guest who may receive extra care or a special treatment.', short:'A very important guest' },
  { word:'Walk-in', th:'ลูกค้าที่มาโดยไม่ได้จอง', phon:'/ˈwɔːk.ɪn/', cat:'care', def:'A guest who arrives without a prior booking.', short:'A guest with no prior booking' },
  { word:'Referral', th:'การแนะนำบอกต่อ', phon:'/rɪˈfɜː.rəl/', cat:'care', def:'A recommendation from one guest that brings a new guest to the spa.', short:'A recommendation bringing a new guest' },
  { word:'Membership', th:'สมาชิกภาพ', phon:'/ˈmem.bə.ʃɪp/', cat:'care', def:'A paid arrangement giving a guest ongoing access to services or discounts.', short:'Paid ongoing access to services' },

  // spa facilities (10)
  { word:'Reception', th:'แผนกต้อนรับ', phon:'/rɪˈsep.ʃən/', cat:'facilities', def:'The front desk area where guests are welcomed and check in.', short:'Front desk welcome area' },
  { word:'Relaxation lounge', th:'ห้องพักผ่อน', phon:'/ˌriː.lækˈseɪ.ʃən laʊndʒ/', cat:'facilities', def:'A quiet area where guests can rest before or after treatments.', short:'A quiet area to rest' },
  { word:'Treatment room', th:'ห้องทรีตเมนต์', phon:'/ˈtriːt.mənt ruːm/', cat:'facilities', def:'A private room where a therapist carries out a spa treatment.', short:'Private room for treatments' },
  { word:'Changing room', th:'ห้องเปลี่ยนเสื้อผ้า', phon:'/ˈtʃeɪn.dʒɪŋ ruːm/', cat:'facilities', def:'A room where guests can change clothes and store their belongings.', short:'Room to change and store items' },
  { word:'Robe', th:'เสื้อคลุมอาบน้ำ', phon:'/rəʊb/', cat:'facilities', def:'A soft, loose garment worn by guests before and after treatments.', short:'Soft loose garment for guests' },
  { word:'Locker', th:'ตู้ล็อกเกอร์', phon:'/ˈlɒk.ər/', cat:'facilities', def:'A small, lockable storage compartment for a guest\u2019s personal belongings.', short:'Lockable personal storage' },
  { word:'Massage table', th:'เตียงนวด', phon:'/məˈsɑːʒ ˈteɪ.bəl/', cat:'facilities', def:'A padded, adjustable table a guest lies on during a massage.', short:'Padded table used for massage' },
  { word:'Essential oil', th:'น้ำมันหอมระเหย', phon:'/ɪˈsen.ʃəl ɔɪl/', cat:'facilities', def:'A concentrated plant extract used in aromatherapy and massage.', short:'Concentrated plant extract' },
  { word:'Diffuser', th:'เครื่องพ่นไอน้ำมันหอม', phon:'/dɪˈfjuː.zər/', cat:'facilities', def:'A device that disperses a fine mist of scented oil into the air.', short:'Disperses scented mist into air' },
  { word:'Ambience', th:'บรรยากาศ', phon:'/ˈæm.bi.əns/', cat:'facilities', def:'The overall atmosphere or mood created by lighting, music and scent.', short:'The overall mood of a space' },

  // wellness & body (10)
  { word:'Circulation', th:'การไหลเวียนโลหิต', phon:'/ˌsɜː.kjəˈleɪ.ʃən/', cat:'wellness', def:'The movement of blood around the body.', short:'Movement of blood in the body' },
  { word:'Muscle tension', th:'กล้ามเนื้อตึงเครียด', phon:'/ˈmʌs.əl ˈten.ʃən/', cat:'wellness', def:'Tightness or stiffness in the muscles, often caused by stress.', short:'Tightness or stiffness in muscles' },
  { word:'Posture', th:'ท่าทางและบุคลิกภาพ', phon:'/ˈpɒs.tʃər/', cat:'wellness', def:'The position in which someone holds their body.', short:'The position of someone\u2019s body' },
  { word:'Wellbeing', th:'สุขภาวะที่ดี', phon:'/ˌwelˈbiː.ɪŋ/', cat:'wellness', def:'A state of feeling comfortable, healthy and content.', short:'Feeling comfortable and healthy' },
  { word:'Mindfulness', th:'สติและการอยู่กับปัจจุบัน', phon:'/ˈmaɪnd.fəl.nəs/', cat:'wellness', def:'The practice of being fully present and aware in the moment.', short:'Being fully present and aware' },
  { word:'Stress relief', th:'การคลายเครียด', phon:'/stres rɪˈliːf/', cat:'wellness', def:'The reduction of physical or mental tension.', short:'Reduction of physical/mental tension' },
  { word:'Detox', th:'การล้างพิษ', phon:'/ˈdiː.tɒks/', cat:'wellness', def:'Short for detoxification — the process of removing unwanted substances from the body.', short:'Removing unwanted substances' },
  { word:'Metabolism', th:'กระบวนการเผาผลาญ', phon:'/məˈtæb.əl.ɪ.zəm/', cat:'wellness', def:'The chemical processes in the body that convert food into energy.', short:'Converts food into energy' },
  { word:'Energy flow', th:'การไหลเวียนพลังงาน', phon:'/ˈen.ə.dʒi fləʊ/', cat:'wellness', def:'In holistic therapies, the movement of vital energy through the body.', short:'Movement of vital energy' },
  { word:'Therapeutic', th:'เพื่อการบำบัดรักษา', phon:'/ˌθer.əˈpjuː.tɪk/', cat:'wellness', def:'Having a healing or restoring effect on the body or mind.', short:'Having a healing effect' },
  { word:'Holistic balance', th:'ความสมดุลแบบองค์รวม', phon:'/həˈlɪs.tɪk ˈbæl.əns/', cat:'wellness', def:'A state of physical and emotional equilibrium that many treatments aim to restore.', short:'Physical + emotional equilibrium' },

  // teamwork & shift talk (14) — language staff use with each other, not guests
  { word:'Shift handover', th:'การส่งต่อเวร', phon:'/ʃɪft ˈhæn.dəʊ.və/', cat:'team', def:'Passing information about guests and rooms to the next team coming on duty.', short:'Passing info to the next shift' },
  { word:'Rota', th:'ตารางเวร', phon:'/ˈrəʊ.tə/', cat:'team', def:'The schedule showing which staff work which shifts.', short:'The staff shift schedule' },
  { word:'Cover a shift', th:'ทำงานแทนกะ', phon:'/ˈkʌv.ər ə ʃɪft/', cat:'team', def:'To work a colleague\u2019s shift when they cannot attend.', short:'Work a colleague\u2019s shift' },
  { word:'Restock', th:'เติมของ', phon:'/ˌriːˈstɒk/', cat:'team', def:'To refill supplies such as towels, oils or robes.', short:'Refill supplies' },
  { word:'Turnaround', th:'เวลาจัดห้องใหม่', phon:'/ˈtɜːn.ə.raʊnd/', cat:'team', def:'The time needed to clean and reset a room between guests.', short:'Resetting a room between guests' },
  { word:'Linen', th:'ผ้าปูและผ้าเช็ดตัว', phon:'/ˈlɪn.ɪn/', cat:'team', def:'The sheets, towels and robes used in treatments.', short:'Sheets, towels and robes' },
  { word:'Stocktake', th:'การตรวจนับสินค้า', phon:'/ˈstɒk.teɪk/', cat:'team', def:'Counting all products and supplies to check what needs ordering.', short:'Counting stock and supplies' },
  { word:'Double-booked', th:'จองซ้อนกัน', phon:'/ˌdʌb.əlˈbʊkt/', cat:'team', def:'When two guests have accidentally been given the same slot.', short:'Two guests in one slot' },
  { word:'Running behind', th:'ล่าช้ากว่ากำหนด', phon:'/ˈrʌn.ɪŋ bɪˈhaɪnd/', cat:'team', def:'Working later than the scheduled time, so later guests may wait.', short:'Later than scheduled' },
  { word:'Briefing', th:'การประชุมสรุปงาน', phon:'/ˈbriː.fɪŋ/', cat:'team', def:'A short team meeting before service to share the day\u2019s plan.', short:'Short pre-shift team meeting' },
  { word:'Escalate', th:'ส่งต่อให้หัวหน้า', phon:'/ˈes.kə.leɪt/', cat:'team', def:'To pass a problem to a manager or someone more senior.', short:'Pass a problem to a manager' },
  { word:'Incident report', th:'รายงานอุบัติการณ์', phon:'/ˈɪn.sɪ.dənt rɪˈpɔːt/', cat:'team', def:'A written record of an accident, injury or unusual event.', short:'Written record of an accident' },
  { word:'Grooming standard', th:'มาตรฐานการแต่งกาย', phon:'/ˈgruː.mɪŋ ˈstæn.dəd/', cat:'team', def:'The rules on uniform, hair, nails and presentation at work.', short:'Uniform and presentation rules' },
  { word:'Probation period', th:'ช่วงทดลองงาน', phon:'/prəˈbeɪ.ʃən ˈpɪə.ri.əd/', cat:'team', def:'The first months in a new job, when performance is being assessed.', short:'Trial months in a new job' },

  // additional massage & bodywork (4)
  { word:'Prenatal massage', th:'นวดสำหรับคุณแม่ตั้งครรภ์', phon:'/ˌpriːˈneɪ.təl ˈmæs.ɑːʒ/', cat:'massage', def:'A gentle massage adapted for pregnant guests, using safe positions and pressure.', short:'Gentle massage for pregnancy' },
  { word:'Bolster', th:'หมอนรองตัว', phon:'/ˈbəʊl.stə/', cat:'massage', def:'A firm cushion used to support the body comfortably during treatment.', short:'Firm support cushion' },
  { word:'Draping', th:'การคลุมผ้าให้ลูกค้า', phon:'/ˈdreɪ.pɪŋ/', cat:'massage', def:'Covering a guest with towels or sheets so only the area being worked on is exposed.', short:'Covering a guest with towels' },
  { word:'Knot', th:'กล้ามเนื้อเป็นก้อน', phon:'/nɒt/', cat:'massage', def:'A tight, hardened band of muscle that a guest often feels as a lump.', short:'Tight, hardened band of muscle' },

  // additional facial & skincare (4)
  { word:'Dehydrated skin', th:'ผิวขาดน้ำ', phon:'/ˌdiːˈhaɪ.dreɪ.tɪd skɪn/', cat:'skin', def:'Skin lacking water, which can look dull and feel tight even if it is oily.', short:'Skin lacking water, looks dull' },
  { word:'Congested skin', th:'ผิวอุดตัน', phon:'/kənˈdʒes.tɪd skɪn/', cat:'skin', def:'Skin with blocked pores, often with bumps or blackheads.', short:'Skin with blocked pores' },
  { word:'Ampoule', th:'แอมพูลบำรุงผิว', phon:'/ˈæm.puːl/', cat:'skin', def:'A small sealed vial of concentrated treatment applied in a course.', short:'Small vial of concentrated treatment' },
  { word:'Sheet mask', th:'มาส์กแผ่น', phon:'/ʃiːt mɑːsk/', cat:'skin', def:'A pre-soaked fabric mask laid over the face to deliver active ingredients.', short:'Pre-soaked fabric face mask' },

  // additional safety & hygiene (4)
  { word:'Hypoallergenic', th:'ไม่ก่อให้เกิดอาการแพ้', phon:'/ˌhaɪ.pəʊ.æl.əˈdʒen.ɪk/', cat:'safety', def:'Formulated to reduce the chance of an allergic reaction.', short:'Unlikely to cause a reaction' },
  { word:'Fragrance-free', th:'ปลอดน้ำหอม', phon:'/ˈfreɪ.grəns friː/', cat:'safety', def:'Containing no added perfume, suitable for sensitive guests.', short:'No added perfume' },
  { word:'Slip hazard', th:'พื้นลื่นเสี่ยงอันตราย', phon:'/slɪp ˈhæz.əd/', cat:'safety', def:'A wet or oily floor that could cause someone to fall.', short:'Wet floor risk of falling' },
  { word:'Aftercare leaflet', th:'เอกสารแนะนำหลังทำ', phon:'/ˈɑːf.tə.keə ˈliːf.lət/', cat:'safety', def:'A printed sheet telling guests how to look after themselves after treatment.', short:'Printed post-treatment advice' },

  // additional client care & front desk (5)
  { word:'No-show', th:'ลูกค้าไม่มาตามนัด', phon:'/ˈnəʊ.ʃəʊ/', cat:'care', def:'A guest who books but does not arrive and does not cancel.', short:'Booked but never arrived' },
  { word:'Peak hours', th:'ช่วงเวลาที่คนใช้บริการมาก', phon:'/piːk aʊəz/', cat:'care', def:'The busiest times of the day or week at the spa.', short:'The busiest times' },
  { word:'Add-on treatment', th:'บริการเสริม', phon:'/ˈæd.ɒn ˈtriːt.mənt/', cat:'care', def:'A short extra service a guest can add to their main booking.', short:'Short extra service' },
  { word:'Package deal', th:'แพ็กเกจราคาพิเศษ', phon:'/ˈpæk.ɪdʒ diːl/', cat:'care', def:'Several treatments sold together at a reduced total price.', short:'Treatments bundled at a lower price' },
  { word:'Testimonial', th:'คำรับรองจากลูกค้า', phon:'/ˌtes.tɪˈməʊ.ni.əl/', cat:'care', def:'A positive written comment from a guest about their experience.', short:'Positive written guest comment' },

  // additional facilities (3)
  { word:'Plunge pool', th:'สระน้ำเย็น', phon:'/plʌndʒ puːl/', cat:'facilities', def:'A small, cold pool used briefly after heat treatments.', short:'Small cold pool after heat' },
  { word:'Vichy shower', th:'ฝักบัววิชี่', phon:'/ˈviː.ʃi ˈʃaʊ.ə/', cat:'facilities', def:'A row of overhead jets that rain warm water over a guest lying down.', short:'Overhead rain-jet shower' },
  { word:'Couples suite', th:'ห้องทรีตเมนต์คู่', phon:'/ˈkʌp.əlz swiːt/', cat:'facilities', def:'A treatment room set up for two guests side by side.', short:'Room for two guests together' },
];

/* ---------- PRONUNCIATION (10 tricky terms) ---------- */
const PRON = [
  { word:'Acupressure', th:'การกดจุด', phon:'/ˈæk.juːˌpreʃ.ər/', syll:['a','cu','pres','sure'], stress:2, example:'We\u2019ll begin with gentle acupressure across your shoulders.' },
  { word:'Exfoliation', th:'การขัดผิว', phon:'/ˌeks.fəʊ.liˈeɪ.ʃən/', syll:['ex','fo','li','a','tion'], stress:3, example:'This exfoliation scrub will leave your skin feeling smooth.' },
  { word:'Contraindication', th:'ข้อห้ามในการทำทรีตเมนต์', phon:'/ˌkɒn.trə.ɪn.dɪˈkeɪ.ʃən/', syll:['con','tra','in','di','ca','tion'], stress:4, example:'Please tell us about any contraindications before we start.' },
  { word:'Aromatherapy', th:'สุคนธบำบัด', phon:'/əˌrəʊ.məˈθer.ə.pi/', syll:['a','ro','ma','ther','a','py'], stress:3, example:'Our aromatherapy blend uses lavender and eucalyptus.' },
  { word:'Rejuvenating', th:'ฟื้นฟูความอ่อนเยาว์', phon:'/rɪˈdʒuː.və.neɪ.tɪŋ/', syll:['re','ju','ve','na','ting'], stress:1, example:'This facial is deeply rejuvenating for tired-looking skin.' },
  { word:'Lymphatic', th:'เกี่ยวกับน้ำเหลือง', phon:'/lɪmˈfæt.ɪk/', syll:['lym','phat','ic'], stress:1, example:'Lymphatic drainage can help reduce puffiness around the eyes.' },
  { word:'Therapeutic', th:'เพื่อการบำบัดรักษา', phon:'/ˌθer.əˈpjuː.tɪk/', syll:['the','ra','peu','tic'], stress:2, example:'This warm oil has a therapeutic effect on sore muscles.' },
  { word:'Microdermabrasion', th:'การขัดผิวหน้าด้วยเครื่อง', phon:'/ˌmaɪ.krəʊˌdɜː.məˈbreɪ.ʒən/', syll:['mi','cro','der','ma','bra','sion'], stress:4, example:'Microdermabrasion works well before a special occasion.' },
  { word:'Reflexology', th:'การนวดกดจุดฝ่าเท้า', phon:'/ˌriː.flekˈsɒl.ə.dʒi/', syll:['re','flex','ol','o','gy'], stress:1, example:'Reflexology focuses entirely on the feet and lower legs.' },
  { word:'Complimentary', th:'บริการฟรี', phon:'/ˌkɒm.plɪˈmen.tər.i/', syll:['com','pli','men','ta','ry'], stress:2, example:'Your consultation today is complimentary.' },
  { word:'Hypoallergenic', th:'ไม่ก่อให้เกิดอาการแพ้', phon:'/ˌhaɪ.pəʊ.æl.əˈdʒen.ɪk/', syll:['hy','po','al','ler','gen','ic'], stress:4, example:'All of our facial products are hypoallergenic.' },
  { word:'Petrissage', th:'การนวดคลึงกล้ามเนื้อ', phon:'/ˈpet.rɪ.sɑːʒ/', syll:['pe','tris','sage'], stress:0, example:'I\u2019ll use petrissage to work into that tight shoulder.' },
  { word:'Effleurage', th:'การนวดลูบผิวเบาๆ', phon:'/ˌef.lɜːˈrɑːʒ/', syll:['ef','fleu','rage'], stress:2, example:'We always begin with effleurage to warm the muscles.' },
  { word:'Dehydrated', th:'ขาดน้ำ', phon:'/ˌdiːˈhaɪ.dreɪ.tɪd/', syll:['de','hy','dra','ted'], stress:1, example:'Your skin looks a little dehydrated today.' },
  { word:'Itinerary', th:'กำหนดการ', phon:'/aɪˈtɪn.ər.ər.i/', syll:['i','tin','e','ra','ry'], stress:1, example:'Here is your spa itinerary for this afternoon.' },
  { word:'Congested', th:'อุดตัน', phon:'/kənˈdʒes.tɪd/', syll:['con','ges','ted'], stress:1, example:'The skin around your nose is slightly congested.' },
  { word:'Turnaround', th:'เวลาจัดห้องใหม่', phon:'/ˈtɜːn.ə.raʊnd/', syll:['turn','a','round'], stress:0, example:'We have a fifteen-minute turnaround before the next guest.' },
];

/* ---------- USEFUL PHRASES (8 categories, ~55 lines) ---------- */
const PHRASES = [
  { id:'welcome', en:'Welcoming guests', th:'การต้อนรับแขก', items:[
    { text:'Good afternoon, welcome to Willow & Stone. How may I assist you today?', th:'สวัสดีตอนบ่ายค่ะ ยินดีต้อนรับสู่วิลโลว์แอนด์สโตน มีอะไรให้ดิฉันช่วยไหมคะ', note:'A warm, formal opener for arrival.' },
    { text:'Thank you for choosing us today — may I take your coat and bag?', th:'ขอบคุณที่เลือกใช้บริการเรานะคะ ขอรับเสื้อโค้ทและกระเป๋าได้ไหมคะ', note:'Offers immediate, practical help.' },
    { text:'Right this way, please. Let me show you to our relaxation lounge.', th:'เชิญทางนี้ค่ะ ดิฉันจะพาไปที่ห้องพักผ่อน', note:'A polite way to guide a guest.' },
    { text:'Is this your first visit with us? I\u2019d be happy to explain how everything works.', th:'นี่เป็นครั้งแรกที่มาใช้บริการกับเราใช่ไหมคะ ดิฉันยินดีอธิบายขั้นตอนต่างๆ ให้ฟัง', note:'Puts first-time guests at ease.' },
    { text:'Please make yourself comfortable — your therapist will be with you shortly.', th:'เชิญนั่งพักตามสบายนะคะ นักบำบัดของคุณจะมาถึงในอีกสักครู่', note:'Reassures a guest who is waiting.' },
    { text:'Welcome back! It\u2019s lovely to see you again.', th:'ยินดีต้อนรับกลับมาอีกครั้งค่ะ ดีใจที่ได้เจอกันอีก', note:'A warm greeting for a returning guest.' },
    { text:'Can I get you some water, tea, or a cold towel while you wait?', th:'รับน้ำ ชา หรือผ้าเย็นระหว่างรอไหมคะ', note:'A thoughtful gesture while a guest waits.' },
    { text:'Your therapist today will be Nok — she has fifteen years of experience.', th:'นักบำบัดของคุณวันนี้ชื่อนกค่ะ มีประสบการณ์สิบห้าปี', note:'Builds confidence in the assigned therapist.' },
  ]},
  { id:'explain', en:'Explaining treatments', th:'การอธิบายทรีตเมนต์', items:[
    { text:'Today\u2019s treatment includes a full-body exfoliation, followed by a hydrating mask.', th:'ทรีตเมนต์วันนี้ประกอบด้วยการขัดผิวทั้งตัว ตามด้วยมาส์กให้ความชุ่มชื้น', note:'Sets out clear expectations.' },
    { text:'This massage focuses on releasing tension through your shoulders and lower back.', th:'การนวดนี้เน้นคลายความตึงเครียดบริเวณไหล่และหลังส่วนล่าง', note:'Describes the purpose of the treatment.' },
    { text:'We\u2019ll be using a warm oil blend of lavender and chamomile to help you relax.', th:'เราจะใช้น้ำมันกลิ่นลาเวนเดอร์และคาโมมายล์เพื่อช่วยให้คุณผ่อนคลาย', note:'Names the products being used.' },
    { text:'The session runs for around sixty minutes, with time to relax afterward.', th:'คอร์สนี้ใช้เวลาประมาณหกสิบนาที พร้อมเวลาพักผ่อนหลังจบทรีตเมนต์', note:'States the duration clearly.' },
    { text:'May I ask if you have any allergies or sensitivities I should know about?', th:'ขอถามหน่อยได้ไหมคะว่าคุณมีอาการแพ้หรือผิวแพ้ง่ายหรือเปล่า', note:'An essential safety question.' },
    { text:'This oil blend is completely natural and suitable for sensitive skin.', th:'น้ำมันสูตรนี้เป็นธรรมชาติทั้งหมดและเหมาะกับผิวแพ้ง่าย', note:'Reassures a cautious guest about ingredients.' },
    { text:'Please let me know if you\u2019ve had this treatment before.', th:'รบกวนแจ้งด้วยนะคะถ้าเคยทำทรีตเมนต์นี้มาก่อน', note:'Helps you tailor the explanation.' },
  ]},
  { id:'comfort', en:'Checking comfort levels', th:'การตรวจสอบความสบาย', items:[
    { text:'How does that pressure feel? Let me know if you\u2019d like it firmer or lighter.', th:'แรงกดตรงนั้นเป็นอย่างไรบ้างคะ บอกได้เลยถ้าอยากให้หนักขึ้นหรือเบาลง', note:'Invites honest, in-the-moment feedback.' },
    { text:'Is the room temperature comfortable for you?', th:'อุณหภูมิห้องสบายไหมคะ', note:'A simple, direct comfort check.' },
    { text:'Please say at any point if you\u2019d like a short break or a glass of water.', th:'บอกได้ทุกเมื่อนะคะถ้าอยากพักหรือดื่มน้ำ', note:'Shows ongoing attentiveness.' },
    { text:'Are you comfortable turning onto your back for the next part of the treatment?', th:'สบายไหมคะถ้าจะพลิกตัวนอนหงายสำหรับขั้นตอนต่อไป', note:'Confirms position changes politely.' },
    { text:'If anything feels uncomfortable, just say so and I\u2019ll adjust it right away.', th:'ถ้ามีตรงไหนรู้สึกไม่สบายตัว บอกได้เลยนะคะ จะปรับให้ทันที', note:'Gives the guest permission to speak up.' },
    { text:'You\u2019re doing great — just breathe naturally and let your body relax.', th:'ทำได้ดีมากค่ะ หายใจตามปกติแล้วปล่อยตัวให้ผ่อนคลาย', note:'Calms a guest who seems tense.' },
    { text:'Would you prefer more or less conversation during your treatment?', th:'อยากให้คุยด้วยระหว่างทรีตเมนต์ หรืออยากเงียบๆ คะ', note:'Respects a guest\u2019s preferred experience.' },
  ]},
  { id:'booking', en:'Bookings & payment', th:'การจองและการชำระเงิน', items:[
    { text:'Would you like to book your next appointment before you leave today?', th:'อยากจองคิวครั้งต่อไปก่อนกลับวันนี้ไหมคะ', note:'A gentle, non-pushy rebooking prompt.' },
    { text:'I\u2019m afraid that slot has just been taken — could ten thirty work instead?', th:'ขออภัยค่ะ คิวนั้นเพิ่งมีคนจองไป สิบโมงครึ่งสะดวกไหมคะ', note:'Declines while offering an alternative.' },
    { text:'That will be sixty-five pounds today — would you like to pay by card or cash?', th:'ราคาวันนี้หกสิบห้าปอนด์ค่ะ ชำระด้วยบัตรหรือเงินสดคะ', note:'States the price plainly and clearly.' },
    { text:'I can add you to our waiting list in case an earlier slot becomes free.', th:'ดิฉันสามารถใส่ชื่อคุณในรายชื่อรอคิวได้ เผื่อมีคิวว่างเร็วขึ้น', note:'A helpful option when fully booked.' },
    { text:'Your loyalty points have been updated — you\u2019re close to your next reward.', th:'คะแนนสะสมของคุณอัปเดตแล้วค่ะ ใกล้ได้รับรางวัลครั้งต่อไปแล้ว', note:'Recognises a returning guest.' },
    { text:'Could I take a small deposit to secure your booking?', th:'ขอรับมัดจำเล็กน้อยเพื่อยืนยันการจองได้ไหมคะ', note:'Explains a deposit request politely.' },
    { text:'Your appointment is confirmed for Saturday at ten in the morning.', th:'การนัดหมายของคุณยืนยันแล้วสำหรับวันเสาร์ เวลาสิบโมงเช้า', note:'Confirms the details clearly.' },
  ]},
  { id:'aftercare', en:'Aftercare advice', th:'คำแนะนำหลังทรีตเมนต์', items:[
    { text:'We recommend drinking plenty of water over the next twenty-four hours.', th:'แนะนำให้ดื่มน้ำมากๆ ในช่วงยี่สิบสี่ชั่วโมงข้างหน้า', note:'Standard, simple hydration guidance.' },
    { text:'Please avoid direct sun exposure for at least forty-eight hours after this facial.', th:'หลีกเลี่ยงแสงแดดโดยตรงอย่างน้อยสี่สิบแปดชั่วโมงหลังทำเฟเชียล', note:'Clear sun-protection guidance.' },
    { text:'You may feel a little tender tomorrow — that\u2019s completely normal after deep tissue work.', th:'พรุ่งนี้อาจรู้สึกเมื่อยเล็กน้อย ถือเป็นเรื่องปกติหลังนวดเนื้อเยื่อส่วนลึก', note:'Sets expectations kindly.' },
    { text:'For the best results, we\u2019d suggest a follow-up session in two to three weeks.', th:'เพื่อผลลัพธ์ที่ดีที่สุด แนะนำให้มาอีกครั้งในอีกสองถึงสามสัปดาห์', note:'Encourages rebooking naturally.' },
    { text:'Here\u2019s a card listing the products we used, in case you\u2019d like to try them at home.', th:'นี่คือรายการผลิตภัณฑ์ที่เราใช้วันนี้ เผื่อสนใจนำไปใช้ต่อที่บ้าน', note:'A soft, low-pressure product mention.' },
    { text:'Try to avoid strenuous exercise for the rest of today.', th:'พยายามหลีกเลี่ยงการออกกำลังกายหนักๆ ในวันนี้', note:'Simple activity guidance.' },
    { text:'If you notice any unusual redness or irritation, please contact us.', th:'หากสังเกตเห็นรอยแดงหรือระคายเคืองผิดปกติ กรุณาติดต่อเรา', note:'Clear guidance on when to follow up.' },
  ]},
  { id:'closing', en:'Closing & farewell', th:'การกล่าวลา', items:[
    { text:'That brings us to the end of your session — take your time getting up.', th:'ทรีตเมนต์วันนี้จบแล้วค่ะ ค่อยๆ ลุกนะคะไม่ต้องรีบ', note:'A gentle way to close a treatment.' },
    { text:'I hope you leave feeling wonderfully relaxed. It was a pleasure looking after you.', th:'หวังว่าคุณจะรู้สึกผ่อนคลายมากๆ นะคะ เป็นเกียรติที่ได้ดูแลคุณวันนี้', note:'A warm, personal send-off.' },
    { text:'Thank you again for visiting — we hope to see you again soon.', th:'ขอบคุณอีกครั้งที่มาใช้บริการนะคะ หวังว่าจะได้พบกันอีก', note:'A simple, sincere goodbye.' },
    { text:'Your feedback means a lot to us, so please do let us know how everything felt.', th:'ความคิดเห็นของคุณมีความหมายกับเรามาก รบกวนบอกเราด้วยนะคะว่ารู้สึกอย่างไรบ้าง', note:'Invites useful feedback naturally.' },
    { text:'Please take this small gift as a thank-you for visiting us today.', th:'รับของขวัญเล็กๆ น้อยๆ นี้เป็นการขอบคุณที่มาวันนี้นะคะ', note:'A generous, memorable closing touch.' },
    { text:'Safe travels, and we look forward to welcoming you back.', th:'เดินทางปลอดภัยนะคะ แล้วหวังว่าจะได้ต้อนรับคุณอีกครั้ง', note:'A caring final line as guests leave.' },
  ]},
  { id:'concerns', en:'Handling concerns', th:'การจัดการข้อร้องเรียน', items:[
    { text:'I\u2019m so sorry to hear that — let me see how I can put this right.', th:'ดิฉันเสียใจมากที่ได้ยินแบบนั้นค่ะ ขอดูก่อนนะคะว่าจะช่วยแก้ไขอย่างไรได้บ้าง', note:'Opens with empathy, not excuses.' },
    { text:'Thank you for bringing this to our attention.', th:'ขอบคุณที่แจ้งเรื่องนี้ให้เราทราบนะคะ', note:'Treats feedback as valuable, not a threat.' },
    { text:'Would you like us to adjust the treatment, or would you prefer to stop?', th:'อยากให้ปรับทรีตเมนต์ หรืออยากหยุดเลยดีคะ', note:'Gives the guest real, immediate control.' },
    { text:'I completely understand your frustration, and I\u2019ll speak with my manager right away.', th:'ดิฉันเข้าใจความรู้สึกไม่พอใจของคุณอย่างเต็มที่ และจะรีบแจ้งผู้จัดการทันที', note:'Validates feelings and shows urgency.' },
    { text:'As an apology, we\u2019d like to offer you a complimentary treatment on your next visit.', th:'เพื่อเป็นการขอโทษ เราอยากมอบทรีตเมนต์ฟรีให้ในครั้งหน้านะคะ', note:'A concrete, generous gesture.' },
    { text:'I want to make sure you leave feeling happy with today\u2019s experience.', th:'ดิฉันอยากให้แน่ใจว่าคุณจะกลับไปด้วยความพึงพอใจกับวันนี้', note:'States your genuine intention plainly.' },
    { text:'Let me get my supervisor so we can resolve this together.', th:'ขอไปตามหัวหน้างานมาช่วยแก้ไขเรื่องนี้ด้วยกันนะคะ', note:'Knowing when to involve a manager.' },
  ]},
  { id:'smalltalk', en:'Small talk with guests', th:'การสนทนาทั่วไปกับแขก', items:[
    { text:'Have you visited Sriracha before, or is this your first time?', th:'เคยมาศรีราชามาก่อนไหมคะ หรือนี่เป็นครั้งแรก', note:'Opens conversation without being intrusive.' },
    { text:'The weather has been very warm this week, hasn\u2019t it?', th:'อาทิตย์นี้อากาศร้อนมากเลยนะคะ', note:'A safe, easy opener in any country.' },
    { text:'Are you staying nearby, or travelling in for the day?', th:'พักแถวนี้ หรือเดินทางมาแบบไปกลับคะ', note:'Useful for recommending timings.' },
    { text:'Please let me know if you\u2019d rather relax quietly \u2014 that\u2019s completely fine.', th:'บอกได้เลยนะคะถ้าอยากพักผ่อนแบบเงียบๆ ไม่เป็นไรเลยค่ะ', note:'Gives the guest permission to end small talk.' },
    { text:'I hope you enjoy the rest of your stay in Thailand.', th:'หวังว่าคุณจะสนุกกับการพักผ่อนที่เมืองไทยนะคะ', note:'A warm closing line for visitors.' },
    { text:'That\u2019s a lovely choice \u2014 it\u2019s one of our most popular treatments.', th:'เลือกได้ดีมากค่ะ เป็นทรีตเมนต์ที่ได้รับความนิยมที่สุดอันหนึ่งของเรา', note:'Affirms the guest\u2019s decision naturally.' },
  ]},
  { id:'teamwork', en:'Talking with your team', th:'การสื่อสารกับทีมงาน', items:[
    { text:'Could you cover room three for me? I\u2019m running a few minutes behind.', th:'ช่วยดูแลห้องสามแทนได้ไหม ฉันช้าไปสองสามนาที', note:'Asking a colleague for help clearly.' },
    { text:'Room two needs a turnaround before the two o\u2019clock guest.', th:'ห้องสองต้องจัดใหม่ก่อนแขกรอบบ่ายสองนะ', note:'Practical handover instruction.' },
    { text:'We\u2019re low on towels \u2014 could someone restock the linen cupboard?', th:'ผ้าเช็ดตัวเหลือน้อยแล้ว ใครช่วยเติมในตู้ผ้าได้ไหม', note:'Flagging a supply issue.' },
    { text:'Just to hand over: the guest in room one prefers very light pressure.', th:'ขอส่งต่อข้อมูลนะ แขกห้องหนึ่งชอบให้กดเบาๆ มาก', note:'A clean, useful shift handover.' },
    { text:'I think we\u2019re double-booked at four \u2014 could you check the diary?', th:'คิดว่าสี่โมงจองซ้อนกันนะ ช่วยเช็กตารางนัดได้ไหม', note:'Raising a scheduling problem politely.' },
    { text:'Would you mind if I escalated this to the manager?', th:'ขอส่งเรื่องนี้ให้ผู้จัดการได้ไหม', note:'Knowing when and how to escalate.' },
    { text:'Thanks for stepping in earlier \u2014 that really helped.', th:'ขอบคุณที่มาช่วยเมื่อกี้นะ ช่วยได้มากเลย', note:'Recognising a colleague\u2019s support.' },
    { text:'Shall we run through the briefing before we open?', th:'มาสรุปงานกันก่อนเปิดร้านไหม', note:'Starting a pre-shift meeting.' },
  ]},
  { id:'upsell', en:'Suggesting extras politely', th:'การแนะนำบริการเสริมอย่างสุภาพ', items:[
    { text:'Would you like to add a thirty-minute foot massage to today\u2019s treatment?', th:'สนใจเพิ่มนวดเท้าสามสิบนาทีกับทรีตเมนต์วันนี้ไหมคะ', note:'A clear, low-pressure add-on offer.' },
    { text:'Many guests pair this facial with a scalp massage \u2014 shall I explain it?', th:'แขกหลายท่านนิยมทำเฟเชียลนี้คู่กับนวดศีรษะ ให้อธิบายเพิ่มไหมคะ', note:'Uses social proof instead of pressure.' },
    { text:'If you\u2019re visiting often, our package deal may work out better value.', th:'ถ้ามาใช้บริการบ่อย แพ็กเกจของเราอาจคุ้มค่ากว่านะคะ', note:'Frames an upsell as a saving.' },
    { text:'No problem at all if you\u2019d rather keep it as it is.', th:'ไม่เป็นไรเลยค่ะ ถ้าอยากทำแบบเดิมก็ได้', note:'Essential: always give an easy way out.' },
    { text:'This oil is the one we used today, if you\u2019d like to take some home.', th:'น้ำมันที่เราใช้วันนี้คือขวดนี้ค่ะ ถ้าสนใจซื้อกลับบ้าน', note:'Product mention tied to the experience.' },
    { text:'Shall I hold a slot for you next month while it\u2019s still free?', th:'ให้จองคิวเดือนหน้าไว้เลยไหมคะ ตอนนี้ยังว่างอยู่', note:'Rebooking with a gentle reason to decide.' },
  ]},
  { id:'phone', en:'Phone & online enquiries', th:'การสอบถามทางโทรศัพท์', items:[
    { text:'Good morning, Willow & Stone Spa, this is Praew speaking. How can I help you?', th:'สวัสดีค่ะ วิลโลว์แอนด์สโตนสปา ดิฉันแพรวค่ะ มีอะไรให้ช่วยไหมคะ', note:'A clear, friendly phone greeting.' },
    { text:'Would you like me to check our availability for this Friday?', th:'อยากให้ดิฉันเช็กคิวว่างวันศุกร์นี้ให้ไหมคะ', note:'Moves the call toward booking.' },
    { text:'I\u2019ll just place you on hold for a moment while I check the diary.', th:'ขอโฮลด์สายสักครู่นะคะ ระหว่างที่ดิฉันเช็กตารางนัด', note:'Politely explains a short pause.' },
    { text:'Can I take your name and a contact number for the booking?', th:'ขอชื่อและเบอร์ติดต่อสำหรับการจองได้ไหมคะ', note:'Standard booking information request.' },
    { text:'I\u2019ve sent a confirmation to your email — please let us know if anything looks wrong.', th:'ดิฉันส่งอีเมลยืนยันไปแล้วนะคะ หากมีอะไรผิดพลาดกรุณาแจ้งเราได้เลย', note:'Confirms in writing and invites correction.' },
    { text:'Thank you for calling — we look forward to seeing you soon.', th:'ขอบคุณที่โทรมานะคะ หวังว่าจะได้พบกันเร็วๆ นี้', note:'A warm way to end a phone call.' },
  ]},
];

/* ---------- SAY THIS, NOT THAT (14 scenarios) ---------- */
const SAYTHIS = [
  { scenario:'A guest arrives early', dont:'Wait here.', dontTh:'รอตรงนี้',
    doo:'Please have a seat in our lounge while we finish preparing your room — it won\u2019t be long.',
    dooTh:'เชิญนั่งพักที่ห้องรับรองระหว่างที่เราเตรียมห้องให้นะคะ ใช้เวลาไม่นานค่ะ',
    why:'Gives a warm invitation and a clear time expectation instead of a bare command.' },
  { scenario:'Checking for allergies', dont:'You don\u2019t have any allergies, right?', dontTh:'คุณไม่มีอาการแพ้ใช่ไหม',
    doo:'Could you tell me if you have any allergies or skin sensitivities we should know about?',
    dooTh:'ช่วยบอกได้ไหมคะว่ามีอาการแพ้หรือผิวแพ้ง่ายที่เราควรทราบหรือเปล่า',
    why:'An open question doesn\u2019t assume the answer, so guests are more likely to disclose something important.' },
  { scenario:'Reassuring about temperature', dont:'It\u2019s not hot.', dontTh:'มันไม่ร้อนหรอก',
    doo:'The temperature is gentle and completely safe for your skin.',
    dooTh:'อุณหภูมินี้อ่อนโยนและปลอดภัยกับผิวของคุณอย่างแน่นอนค่ะ',
    why:'Positive, descriptive language reassures rather than simply denying the concern.' },
  { scenario:'A guest is running late', dont:'You\u2019re late, so we have less time now.', dontTh:'คุณมาสาย เวลาก็เลยน้อยลง',
    doo:'No problem at all — we\u2019ll make the very best use of the time we have together.',
    dooTh:'ไม่เป็นไรเลยค่ะ เราจะใช้เวลาที่มีให้คุ้มค่าที่สุด',
    why:'Keeps the guest relaxed instead of making them feel at fault.' },
  { scenario:'Asking a guest to undress', dont:'Take your clothes off and lie down.', dontTh:'ถอดเสื้อผ้าแล้วนอนลง',
    doo:'Please undress to your comfort level and lie face-down under the towel whenever you\u2019re ready.',
    dooTh:'กรุณาถอดเสื้อผ้าเท่าที่คุณสบายใจ แล้วนอนคว่ำใต้ผ้าขนหนูเมื่อพร้อมนะคะ',
    why:'Gives the guest control over their own privacy and comfort.' },
  { scenario:'Recommending a product', dont:'You should buy this, your skin looks bad.', dontTh:'คุณควรซื้ออันนี้ ผิวคุณดูแย่',
    doo:'This would really complement today\u2019s treatment, if you\u2019d like to take a closer look.',
    dooTh:'อันนี้จะช่วยเสริมทรีตเมนต์วันนี้ได้ดีค่ะ ถ้าสนใจลองดูใกล้ๆ ได้นะคะ',
    why:'Avoids any judgement and frames the suggestion as entirely optional.' },
  { scenario:'Ending the session', dont:'Time\u2019s up, you need to leave now.', dontTh:'หมดเวลาแล้ว คุณต้องออกไปตอนนี้',
    doo:'That brings us to the end of your session — please take a moment to relax before you head out.',
    dooTh:'ทรีตเมนต์วันนี้จบแล้วค่ะ พักผ่อนสักครู่ก่อนออกไปได้นะคะ',
    why:'Closes the session warmly rather than rushing the guest out.' },
  { scenario:'Feedback about pressure', dont:'That\u2019s normal pressure, everyone gets the same.', dontTh:'นั่นคือแรงกดปกติ ทุกคนก็ได้แบบนี้',
    doo:'Thank you for telling me — I\u2019ll adjust that for you right away.',
    dooTh:'ขอบคุณที่บอกนะคะ ดิฉันจะปรับให้ทันที',
    why:'Validates the guest\u2019s feedback instead of dismissing it.' },
  { scenario:'Discussing price', dont:'It\u2019s expensive because it\u2019s the best.', dontTh:'มันแพงเพราะมันดีที่สุด',
    doo:'This treatment is a little more, as it includes an extended massage and a hydrating mask.',
    dooTh:'ทรีตเมนต์นี้ราคาสูงขึ้นเล็กน้อยเพราะรวมการนวดที่ยาวขึ้นและมาส์กให้ความชุ่มชื้นค่ะ',
    why:'Explains the value clearly instead of sounding defensive.' },
  { scenario:'Declining a same-day request', dont:'No, we\u2019re full.', dontTh:'ไม่ได้ เราเต็มแล้ว',
    doo:'I\u2019m afraid today is fully booked, but I\u2019d love to find you a time later this week.',
    dooTh:'วันนี้คิวเต็มแล้วค่ะ แต่ดิฉันยินดีหาเวลาให้ในสัปดาห์นี้นะคะ',
    why:'Turns a flat refusal into a genuinely helpful alternative.' },
  { scenario:'Guest asks for a discount', dont:'We don\u2019t do discounts.', dontTh:'เราไม่มีส่วนลด',
    doo:'I can\u2019t reduce today\u2019s price, but I\u2019d be happy to tell you about our loyalty programme.',
    dooTh:'ดิฉันลดราคาวันนี้ไม่ได้ค่ะ แต่ยินดีแนะนำโปรแกรมสมาชิกสะสมแต้มให้นะคะ',
    why:'Redirects to a real, positive alternative rather than a flat no.' },
  { scenario:'Running behind schedule', dont:'The therapist before you took too long.', dontTh:'นักบำบัดคนก่อนใช้เวลานานเกินไป',
    doo:'Thank you for your patience — we\u2019re just running a few minutes behind today.',
    dooTh:'ขอบคุณที่รอนะคะ วันนี้เราล่าช้าไปเล็กน้อยค่ะ',
    why:'Stays professional without blaming a colleague in front of the guest.' },
  { scenario:'Guest wants to skip the form', dont:'You have to fill this in, it\u2019s the rule.', dontTh:'คุณต้องกรอกอันนี้ มันเป็นกฎ',
    doo:'This form helps us keep you safe during treatment — it only takes a moment.',
    dooTh:'แบบฟอร์มนี้ช่วยให้เราดูแลความปลอดภัยของคุณระหว่างทรีตเมนต์ค่ะ ใช้เวลาแค่แป๊บเดียว',
    why:'Explains the reason behind a rule instead of only citing it.' },
  { scenario:'Guest is unhappy with results', dont:'There\u2019s nothing wrong with it.', dontTh:'มันไม่มีอะไรผิดปกติ',
    doo:'Let\u2019s talk through what you were hoping for, so we can make it right.',
    dooTh:'มาคุยกันนะคะว่าคุณคาดหวังผลลัพธ์แบบไหน เพื่อที่เราจะได้แก้ไขให้ถูกต้อง',
    why:'Opens a real conversation instead of dismissing the guest\u2019s feelings.' },
  { scenario:'Guest asks a question you can\u2019t answer', dont:'I don\u2019t know.', dontTh:'ไม่รู้',
    doo:'That\u2019s a good question \u2014 let me find out for you right away.',
    dooTh:'เป็นคำถามที่ดีค่ะ ขอไปหาคำตอบให้ทันทีนะคะ',
    why:'Keeps your credibility and promises action instead of closing the conversation.' },
  { scenario:'Guest speaks limited English', dont:'You don\u2019t understand?', dontTh:'ไม่เข้าใจเหรอ',
    doo:'Let me explain that again more slowly \u2014 please stop me any time.',
    dooTh:'ขออธิบายอีกครั้งแบบช้าๆ นะคะ หยุดถามได้ทุกเมื่อเลยค่ะ',
    why:'Puts the responsibility on your explanation, never on the guest\u2019s ability.' },
  { scenario:'A colleague made the mistake', dont:'That wasn\u2019t me, it was the other therapist.', dontTh:'ไม่ใช่ฉัน เป็นนักบำบัดอีกคน',
    doo:'I\u2019m sorry that happened \u2014 let me put it right for you now.',
    dooTh:'ขออภัยที่เกิดเรื่องนี้ขึ้นค่ะ ขอแก้ไขให้เลยนะคะ',
    why:'Guests experience the spa as one team, so deflecting blame damages that trust.' },
  { scenario:'Guest falls asleep in treatment', dont:'Wake up, we\u2019re finished!', dontTh:'ตื่นแล้ว เสร็จแล้วนะ',
    doo:'Take your time waking up \u2014 there\u2019s no rush at all.',
    dooTh:'ค่อยๆ ตื่นนะคะ ไม่ต้องรีบเลยค่ะ',
    why:'Falling asleep is a compliment, and a gentle wake-up protects that calm.' },
  { scenario:'Guest requests an unsafe treatment', dont:'No, we can\u2019t do that.', dontTh:'ไม่ได้ เราทำไม่ได้',
    doo:'For your safety I\u2019d recommend against that today, but may I suggest an alternative?',
    dooTh:'เพื่อความปลอดภัยของคุณ วันนี้ดิฉันไม่แนะนำค่ะ แต่ขอเสนอทางเลือกอื่นได้ไหมคะ',
    why:'Grounds the refusal in the guest\u2019s wellbeing and still offers a way forward.' },
  { scenario:'Guest is on the phone mid-treatment', dont:'Put your phone away.', dontTh:'เก็บโทรศัพท์ด้วย',
    doo:'Would you like me to pause for a moment while you finish your call?',
    dooTh:'ให้หยุดพักสักครู่ระหว่างที่คุณคุยสายให้เสร็จไหมคะ',
    why:'Offers a courtesy rather than an instruction, and usually solves it faster.' },
];

