/* =========================================================================
   COURSE: NIMMAN Harbour & Horizon English
   English for cruise ship crew — guest services, cabin, dining, bar, deck,
   safety drills, shore excursions and crew handovers.

   Same shape as the spa course, so every activity works unchanged:
   each vocabulary entry has word / th / phon / cat / def / short / level,
   each phrase has level / text / th / note.
   ========================================================================= */

const CRUISE_VOCAB_CATEGORIES = [
  { id:'ship',      en:'Ship & areas',            th:'เรือและพื้นที่ต่างๆ' },
  { id:'cabin',     en:'Cabin & housekeeping',    th:'ห้องพักและแม่บ้าน' },
  { id:'dining',    en:'Dining & bar service',    th:'ห้องอาหารและบาร์' },
  { id:'guest',     en:'Guest services desk',     th:'เคาน์เตอร์บริการผู้โดยสาร' },
  { id:'safety',    en:'Safety & emergency',      th:'ความปลอดภัยและเหตุฉุกเฉิน' },
  { id:'port',      en:'Ports & shore excursions',th:'ท่าเรือและทัวร์ชายฝั่ง' },
  { id:'crew',      en:'Crew life & departments', th:'ชีวิตลูกเรือและแผนกงาน' },
  { id:'care',      en:'Guest care & wellbeing',  th:'การดูแลผู้โดยสาร' },
];

const CRUISE_VOCAB = [
  // ship & areas (12)
  { word:'Gangway', level:1, th:'สะพานขึ้นลงเรือ', phon:'/ˈgæŋ.weɪ/', cat:'ship', def:'The walkway passengers use to board or leave the ship.', short:'Walkway on and off the ship' },
  { word:'Muster station', level:2, th:'จุดรวมพลฉุกเฉิน', phon:'/ˈmʌs.tə ˈsteɪ.ʃən/', cat:'ship', def:'The place a passenger must go in an emergency, shown on their cruise card.', short:'Emergency assembly point' },
  { word:'Promenade deck', level:2, th:'ดาดฟ้าเดินเล่น', phon:'/ˌprɒm.əˈnɑːd dek/', cat:'ship', def:'The open deck that runs around the ship for walking.', short:'Open walking deck' },
  { word:'Lido deck', level:2, th:'ดาดฟ้าสระว่ายน้ำ', phon:'/ˈliː.dəʊ dek/', cat:'ship', def:'The deck with the pools, sun loungers and casual buffet.', short:'Pool and buffet deck' },
  { word:'Atrium', level:3, th:'โถงกลางเรือ', phon:'/ˈeɪ.tri.əm/', cat:'ship', def:'The tall open central lobby of the ship, usually over several decks.', short:'Central multi-deck lobby' },
  { word:'Bridge', level:2, th:'สะพานเดินเรือ', phon:'/brɪdʒ/', cat:'ship', def:'The control room from which the captain navigates the ship.', short:'Where the ship is navigated' },
  { word:'Galley', level:2, th:'ห้องครัวบนเรือ', phon:'/ˈgæl.i/', cat:'ship', def:'The ship\u2019s kitchen.', short:'The ship\u2019s kitchen' },
  { word:'Starboard', level:3, th:'กราบขวาของเรือ', phon:'/ˈstɑː.bəd/', cat:'ship', def:'The right-hand side of the ship when facing forward.', short:'Right side of the ship' },
  { word:'Port side', level:3, th:'กราบซ้ายของเรือ', phon:'/pɔːt saɪd/', cat:'ship', def:'The left-hand side of the ship when facing forward.', short:'Left side of the ship' },
  { word:'Bow', level:2, th:'หัวเรือ', phon:'/baʊ/', cat:'ship', def:'The front of the ship.', short:'The front of the ship' },
  { word:'Stern', level:2, th:'ท้ายเรือ', phon:'/stɜːn/', cat:'ship', def:'The back of the ship.', short:'The back of the ship' },
  { word:'Deck plan', level:1, th:'แผนผังชั้นเรือ', phon:'/dek plæn/', cat:'ship', def:'A map showing what is on each deck of the ship.', short:'Map of each deck' },

  // cabin & housekeeping (12)
  { word:'Stateroom', level:2, th:'ห้องพักผู้โดยสาร', phon:'/ˈsteɪt.ruːm/', cat:'cabin', def:'A passenger cabin on a cruise ship.', short:'A passenger cabin' },
  { word:'Cabin steward', level:2, th:'พนักงานดูแลห้องพัก', phon:'/ˈkæb.ɪn ˈstjuː.əd/', cat:'cabin', def:'The crew member who services and cleans a guest\u2019s cabin.', short:'Crew who services cabins' },
  { word:'Turndown service', level:3, th:'บริการจัดเตียงตอนเย็น', phon:'/ˈtɜːn.daʊn ˈsɜː.vɪs/', cat:'cabin', def:'The evening visit to prepare the bed and tidy the cabin for the night.', short:'Evening bed preparation' },
  { word:'Linen change', level:2, th:'การเปลี่ยนผ้าปูเตียง', phon:'/ˈlɪn.ɪn tʃeɪndʒ/', cat:'cabin', def:'Replacing the sheets and towels in a cabin.', short:'Replacing sheets and towels' },
  { word:'Amenities', level:3, th:'ของใช้ในห้องพัก', phon:'/əˈmen.ɪ.tiz/', cat:'cabin', def:'The soap, shampoo and small extras provided in a cabin.', short:'Cabin toiletries and extras' },
  { word:'Balcony cabin', level:1, th:'ห้องพักมีระเบียง', phon:'/ˈbæl.kə.ni ˈkæb.ɪn/', cat:'cabin', def:'A cabin with its own private outdoor balcony.', short:'Cabin with a private balcony' },
  { word:'Interior cabin', level:2, th:'ห้องพักไม่มีหน้าต่าง', phon:'/ɪnˈtɪə.ri.ə ˈkæb.ɪn/', cat:'cabin', def:'A cabin with no window, in the middle of the ship.', short:'Cabin with no window' },
  { word:'Do not disturb sign', level:1, th:'ป้ายห้ามรบกวน', phon:'/duː nɒt dɪˈstɜːb saɪn/', cat:'cabin', def:'The card a guest hangs on the door when they do not want service.', short:'Card asking for no service' },
  { word:'Minibar', level:1, th:'มินิบาร์ในห้อง', phon:'/ˈmɪn.i.bɑː/', cat:'cabin', def:'The small fridge of drinks and snacks in a cabin.', short:'Small in-cabin drinks fridge' },
  { word:'Safe', level:1, th:'ตู้เซฟในห้อง', phon:'/seɪf/', cat:'cabin', def:'The locked box in a cabin for a guest\u2019s valuables.', short:'Locked box for valuables' },
  { word:'Housekeeping trolley', level:2, th:'รถเข็นแม่บ้าน', phon:'/ˈhaʊs.kiː.pɪŋ ˈtrɒl.i/', cat:'cabin', def:'The cart carrying linen and cleaning supplies along the corridor.', short:'Cart with linen and supplies' },
  { word:'Cabin key card', level:1, th:'คีย์การ์ดห้องพัก', phon:'/ˈkæb.ɪn kiː kɑːd/', cat:'cabin', def:'The card that unlocks a guest\u2019s cabin door.', short:'Card that opens the cabin' },

  // dining & bar (14)
  { word:'Maître d\u2019', level:3, th:'หัวหน้าพนักงานต้อนรับห้องอาหาร', phon:'/ˌmeɪ.trəˈdiː/', cat:'dining', def:'The head of the restaurant, who manages seating and service.', short:'Head of the restaurant' },
  { word:'Buffet', level:1, th:'บุฟเฟ่ต์', phon:'/ˈbʊf.eɪ/', cat:'dining', def:'A self-service meal where guests help themselves.', short:'Self-service meal' },
  { word:'À la carte', level:3, th:'สั่งอาหารตามรายการ', phon:'/ˌɑː lɑː ˈkɑːt/', cat:'dining', def:'Ordering individual dishes from a menu rather than a set meal.', short:'Ordering dish by dish' },
  { word:'Seating time', level:2, th:'รอบเวลารับประทานอาหาร', phon:'/ˈsiː.tɪŋ taɪm/', cat:'dining', def:'The allocated dinner sitting a guest is booked for.', short:'The guest\u2019s dinner sitting' },
  { word:'Wine list', level:1, th:'รายการไวน์', phon:'/waɪn lɪst/', cat:'dining', def:'The menu of wines available.', short:'Menu of wines' },
  { word:'Mocktail', level:2, th:'ค็อกเทลไม่มีแอลกอฮอล์', phon:'/ˈmɒk.teɪl/', cat:'dining', def:'A mixed drink with no alcohol.', short:'Alcohol-free cocktail' },
  { word:'Beverage package', level:2, th:'แพ็กเกจเครื่องดื่ม', phon:'/ˈbev.ər.ɪdʒ ˈpæk.ɪdʒ/', cat:'dining', def:'A pre-paid plan covering a guest\u2019s drinks during the cruise.', short:'Pre-paid drinks plan' },
  { word:'Dietary requirement', level:3, th:'ข้อจำกัดด้านอาหาร', phon:'/ˈdaɪ.ə.tər.i rɪˈkwaɪə.mənt/', cat:'dining', def:'A guest\u2019s need to avoid certain foods, for health or belief.', short:'Food a guest must avoid' },
  { word:'Allergy card', level:2, th:'บัตรแจ้งอาการแพ้อาหาร', phon:'/ˈæl.ə.dʒi kɑːd/', cat:'dining', def:'A card recording a guest\u2019s food allergies for the galley.', short:'Card listing food allergies' },
  { word:'Clearing the table', level:1, th:'เก็บโต๊ะอาหาร', phon:'/ˈklɪə.rɪŋ ðə ˈteɪ.bəl/', cat:'dining', def:'Removing used plates and glasses from a table.', short:'Removing used plates' },
  { word:'Service charge', level:2, th:'ค่าบริการ', phon:'/ˈsɜː.vɪs tʃɑːdʒ/', cat:'dining', def:'An amount added to a bill for service.', short:'Amount added for service' },
  { word:'Last call', level:2, th:'สั่งครั้งสุดท้าย', phon:'/lɑːst kɔːl/', cat:'dining', def:'The final chance to order before the bar closes.', short:'Final orders before closing' },
  { word:'Corkage fee', level:3, th:'ค่าเปิดขวด', phon:'/ˈkɔː.kɪdʒ fiː/', cat:'dining', def:'A charge for drinking wine a guest brought aboard themselves.', short:'Charge for your own wine' },
  { word:'Speciality restaurant', level:2, th:'ห้องอาหารพิเศษ', phon:'/ˌspeʃ.iˈæl.ə.ti ˈres.trɒnt/', cat:'dining', def:'A restaurant charging extra for a higher-end menu.', short:'Extra-charge restaurant' },

  // guest services (12)
  { word:'Guest services desk', level:1, th:'เคาน์เตอร์บริการผู้โดยสาร', phon:'/gest ˈsɜː.vɪs.ɪz desk/', cat:'guest', def:'The reception counter where guests bring questions and problems.', short:'Reception counter for guests' },
  { word:'Cruise card', level:1, th:'บัตรประจำตัวผู้โดยสาร', phon:'/kruːz kɑːd/', cat:'guest', def:'A guest\u2019s ID card on board, used as a key and to pay.', short:'Onboard ID, key and payment' },
  { word:'Onboard account', level:2, th:'บัญชีค่าใช้จ่ายบนเรือ', phon:'/ˈɒn.bɔːd əˈkaʊnt/', cat:'guest', def:'The running bill of everything a guest charges during the cruise.', short:'A guest\u2019s running bill' },
  { word:'Folio', level:3, th:'ใบสรุปค่าใช้จ่าย', phon:'/ˈfəʊ.li.əʊ/', cat:'guest', def:'The printed statement of a guest\u2019s onboard charges.', short:'Statement of charges' },
  { word:'Gratuity', level:3, th:'ค่าทิปบริการ', phon:'/grəˈtʃuː.ə.ti/', cat:'guest', def:'A service tip, often added automatically to the onboard account.', short:'Service tip' },
  { word:'Lost property', level:2, th:'ของหาย', phon:'/lɒst ˈprɒp.ə.ti/', cat:'guest', def:'Items guests have left behind, held until claimed.', short:'Items left behind' },
  { word:'Boarding pass', level:1, th:'บัตรขึ้นเรือ', phon:'/ˈbɔː.dɪŋ pɑːs/', cat:'guest', def:'The document allowing a guest to board the ship.', short:'Document to board' },
  { word:'Upgrade', level:2, th:'อัปเกรดห้องพัก', phon:'/ˈʌp.greɪd/', cat:'guest', def:'Moving a guest to a better cabin or service level.', short:'Move to a better cabin' },
  { word:'Loyalty tier', level:3, th:'ระดับสมาชิกสะสมแต้ม', phon:'/ˈlɔɪ.əl.ti tɪə/', cat:'guest', def:'A returning guest\u2019s membership level, which brings extra benefits.', short:'Returning-guest level' },
  { word:'Complimentary', level:3, th:'บริการฟรี', phon:'/ˌkɒm.plɪˈmen.tər.i/', cat:'guest', def:'Provided free of charge.', short:'Free of charge' },
  { word:'Onboard credit', level:2, th:'เครดิตใช้จ่ายบนเรือ', phon:'/ˈɒn.bɔːd ˈkred.ɪt/', cat:'guest', def:'Money given to a guest to spend on board.', short:'Money to spend on board' },
  { word:'Shore excursion desk', level:2, th:'เคาน์เตอร์ทัวร์ชายฝั่ง', phon:'/ʃɔː ɪkˈskɜː.ʃən desk/', cat:'guest', def:'The counter where guests book trips ashore.', short:'Counter for booking trips ashore' },

  // safety & emergency (12)
  { word:'Muster drill', level:2, th:'การซ้อมรวมพลฉุกเฉิน', phon:'/ˈmʌs.tə drɪl/', cat:'safety', def:'The compulsory safety practice all guests attend at the start of a cruise.', short:'Compulsory safety practice' },
  { word:'Life jacket', level:1, th:'เสื้อชูชีพ', phon:'/ˈlaɪf ˌdʒæk.ɪt/', cat:'safety', def:'The vest that keeps a person afloat in water.', short:'Vest that keeps you afloat' },
  { word:'Lifeboat', level:1, th:'เรือชูชีพ', phon:'/ˈlaɪf.bəʊt/', cat:'safety', def:'The small boat used to evacuate people from a ship.', short:'Boat used to evacuate' },
  { word:'Emergency exit', level:1, th:'ทางออกฉุกเฉิน', phon:'/ɪˈmɜː.dʒən.si ˈek.sɪt/', cat:'safety', def:'The marked route out in an emergency.', short:'Marked emergency route' },
  { word:'Safety briefing', level:2, th:'การชี้แจงความปลอดภัย', phon:'/ˈseɪf.ti ˈbriː.fɪŋ/', cat:'safety', def:'The talk explaining what to do in an emergency.', short:'Emergency instructions talk' },
  { word:'General emergency alarm', level:3, th:'สัญญาณฉุกเฉินทั่วไป', phon:'/ˈdʒen.ər.əl ɪˈmɜː.dʒən.si əˈlɑːm/', cat:'safety', def:'Seven short blasts and one long blast, telling everyone to go to their muster station.', short:'Seven short and one long blast' },
  { word:'Man overboard', level:3, th:'คนตกน้ำ', phon:'/mæn ˈəʊ.və.bɔːd/', cat:'safety', def:'The call raised when a person has fallen into the sea.', short:'Someone has fallen in the sea' },
  { word:'Fire door', level:2, th:'ประตูกันไฟ', phon:'/ˈfaɪə dɔː/', cat:'safety', def:'A heavy door that must stay closed to hold back fire.', short:'Door that holds back fire' },
  { word:'Sanitiser station', level:2, th:'จุดเจลล้างมือ', phon:'/ˈsæn.ɪ.taɪ.zə ˈsteɪ.ʃən/', cat:'safety', def:'A hand-hygiene point at entrances to dining areas.', short:'Hand-hygiene point' },
  { word:'Medical centre', level:2, th:'ศูนย์การแพทย์บนเรือ', phon:'/ˈmed.ɪ.kəl ˈsen.tə/', cat:'safety', def:'The ship\u2019s clinic, staffed by a doctor and nurses.', short:'The ship\u2019s clinic' },
  { word:'Crew drill', level:2, th:'การซ้อมของลูกเรือ', phon:'/kruː drɪl/', cat:'safety', def:'A safety exercise for crew only, held regularly.', short:'Crew-only safety exercise' },
  { word:'Restricted area', level:2, th:'พื้นที่หวงห้าม', phon:'/rɪˈstrɪk.tɪd ˈeə.ri.ə/', cat:'safety', def:'A part of the ship guests are not allowed to enter.', short:'Area guests may not enter' },

  // ports & shore excursions (12)
  { word:'Port of call', level:2, th:'ท่าเรือที่แวะจอด', phon:'/pɔːt əv kɔːl/', cat:'port', def:'A place the ship stops so guests can go ashore.', short:'A stop where guests go ashore' },
  { word:'Shore excursion', level:2, th:'ทัวร์ชายฝั่ง', phon:'/ʃɔː ɪkˈskɜː.ʃən/', cat:'port', def:'An organised trip ashore, booked through the ship.', short:'Organised trip ashore' },
  { word:'Tender boat', level:3, th:'เรือเล็กรับส่งขึ้นฝั่ง', phon:'/ˈten.də bəʊt/', cat:'port', def:'A small boat carrying guests ashore where the ship cannot dock.', short:'Small boat to shore' },
  { word:'All aboard time', level:2, th:'เวลากลับขึ้นเรือ', phon:'/ɔːl əˈbɔːd taɪm/', cat:'port', def:'The time by which every guest must be back on the ship.', short:'Deadline to be back on board' },
  { word:'Embarkation', level:3, th:'การขึ้นเรือ', phon:'/ˌem.bɑːˈkeɪ.ʃən/', cat:'port', def:'The process of guests boarding the ship at the start of a cruise.', short:'Boarding the ship' },
  { word:'Disembarkation', level:3, th:'การลงจากเรือ', phon:'/ˌdɪs.em.bɑːˈkeɪ.ʃən/', cat:'port', def:'The process of guests leaving the ship at the end of a cruise.', short:'Leaving the ship' },
  { word:'Itinerary', level:3, th:'กำหนดการเดินเรือ', phon:'/aɪˈtɪn.ər.ər.i/', cat:'port', def:'The planned route and schedule of ports for the cruise.', short:'Planned route and schedule' },
  { word:'Sea day', level:1, th:'วันแล่นเรือกลางทะเล', phon:'/siː deɪ/', cat:'port', def:'A full day at sea with no port stop.', short:'A full day at sea' },
  { word:'Meeting point', level:1, th:'จุดนัดพบ', phon:'/ˈmiː.tɪŋ pɔɪnt/', cat:'port', def:'Where a tour group gathers before setting off.', short:'Where a tour group gathers' },
  { word:'Guided tour', level:1, th:'ทัวร์พร้อมไกด์', phon:'/ˈgaɪ.dɪd tʊə/', cat:'port', def:'A trip led by a guide who explains what you see.', short:'Trip led by a guide' },
  { word:'Local currency', level:2, th:'สกุลเงินท้องถิ่น', phon:'/ˈləʊ.kəl ˈkʌr.ən.si/', cat:'port', def:'The money used in the country the ship is visiting.', short:'Money used in that country' },
  { word:'Customs and immigration', level:3, th:'ด่านศุลกากรและตรวจคนเข้าเมือง', phon:'/ˈkʌs.təmz ənd ˌɪm.ɪˈgreɪ.ʃən/', cat:'port', def:'The official checks on people and goods entering a country.', short:'Official border checks' },

  // crew life & departments (12)
  { word:'Crew mess', level:2, th:'โรงอาหารลูกเรือ', phon:'/kruː mes/', cat:'crew', def:'The crew dining room.', short:'Crew dining room' },
  { word:'Cabin mate', level:1, th:'เพื่อนร่วมห้องพัก', phon:'/ˈkæb.ɪn meɪt/', cat:'crew', def:'The crew member who shares your cabin.', short:'Person sharing your cabin' },
  { word:'Duty roster', level:2, th:'ตารางเวรปฏิบัติงาน', phon:'/ˈdʒuː.ti ˈrɒs.tə/', cat:'crew', def:'The schedule showing who works which shift.', short:'Shift schedule' },
  { word:'Watch', level:2, th:'ช่วงเวลาเข้าเวร', phon:'/wɒtʃ/', cat:'crew', def:'A set period of duty on board.', short:'A set period of duty' },
  { word:'Handover log', level:2, th:'สมุดบันทึกส่งงาน', phon:'/ˈhænd.əʊ.və lɒg/', cat:'crew', def:'The written record passed to the next shift.', short:'Written record for next shift' },
  { word:'Department head', level:2, th:'หัวหน้าแผนก', phon:'/dɪˈpɑːt.mənt hed/', cat:'crew', def:'The manager in charge of a department on board.', short:'Manager of a department' },
  { word:'Sign-on', level:2, th:'เริ่มสัญญาจ้าง', phon:'/ˈsaɪn.ɒn/', cat:'crew', def:'Joining the ship at the start of a contract.', short:'Joining at contract start' },
  { word:'Sign-off', level:2, th:'สิ้นสุดสัญญาจ้าง', phon:'/ˈsaɪn.ɒf/', cat:'crew', def:'Leaving the ship at the end of a contract.', short:'Leaving at contract end' },
  { word:'Shore leave', level:2, th:'วันลาขึ้นฝั่ง', phon:'/ʃɔː liːv/', cat:'crew', def:'Permitted time off the ship while in port.', short:'Time off the ship in port' },
  { word:'Overtime', level:1, th:'ทำงานล่วงเวลา', phon:'/ˈəʊ.və.taɪm/', cat:'crew', def:'Hours worked beyond your normal shift.', short:'Hours beyond your shift' },
  { word:'Crew training', level:1, th:'การอบรมลูกเรือ', phon:'/kruː ˈtreɪ.nɪŋ/', cat:'crew', def:'Sessions teaching crew safety and service standards.', short:'Safety and service sessions' },
  { word:'Contract', level:1, th:'สัญญาจ้างงาน', phon:'/ˈkɒn.trækt/', cat:'crew', def:'The agreement setting out the length and terms of your work on board.', short:'Your work agreement' },

  // guest care & wellbeing (12)
  { word:'Seasickness', level:2, th:'อาการเมาเรือ', phon:'/ˈsiː.sɪk.nəs/', cat:'care', def:'Nausea caused by the movement of the ship.', short:'Nausea from ship movement' },
  { word:'Motion sickness tablet', level:2, th:'ยาแก้เมาเรือ', phon:'/ˈməʊ.ʃən ˈsɪk.nəs ˈtæb.lət/', cat:'care', def:'Medicine that reduces seasickness.', short:'Medicine for seasickness' },
  { word:'Mobility assistance', level:3, th:'ความช่วยเหลือด้านการเคลื่อนไหว', phon:'/məʊˈbɪl.ə.ti əˈsɪs.təns/', cat:'care', def:'Help for guests who find walking or standing difficult.', short:'Help for guests who struggle to walk' },
  { word:'Wheelchair access', level:2, th:'ทางเข้าสำหรับรถเข็น', phon:'/ˈwiːl.tʃeə ˈæk.ses/', cat:'care', def:'A route or facility a wheelchair user can use.', short:'Route usable by a wheelchair' },
  { word:'Priority boarding', level:2, th:'สิทธิ์ขึ้นเรือก่อน', phon:'/praɪˈɒr.ə.ti ˈbɔː.dɪŋ/', cat:'care', def:'Letting certain guests board before the rest.', short:'Boarding before others' },
  { word:'Special assistance', level:2, th:'ความช่วยเหลือเป็นพิเศษ', phon:'/ˈspeʃ.əl əˈsɪs.təns/', cat:'care', def:'Extra help arranged in advance for a guest\u2019s needs.', short:'Pre-arranged extra help' },
  { word:'Quiet zone', level:1, th:'โซนเงียบ', phon:'/ˈkwaɪ.ət zəʊn/', cat:'care', def:'An area of the ship kept free of music and children.', short:'Area kept quiet' },
  { word:'Elderly guest', level:1, th:'ผู้โดยสารสูงอายุ', phon:'/ˈel.dəl.i gest/', cat:'care', def:'An older passenger, who may need more time and care.', short:'An older passenger' },
  { word:'Unaccompanied minor', level:3, th:'ผู้เยาว์เดินทางลำพัง', phon:'/ˌʌn.əˈkʌm.pə.nid ˈmaɪ.nə/', cat:'care', def:'A child travelling without a parent or guardian.', short:'Child travelling alone' },
  { word:'Accessibility', level:3, th:'การเข้าถึงสำหรับทุกคน', phon:'/əkˌses.əˈbɪl.ə.ti/', cat:'care', def:'How easily a place can be used by people with disabilities.', short:'Ease of use for disabled guests' },
  { word:'Curfew', level:2, th:'เวลาห้ามออกนอกห้อง', phon:'/ˈkɜː.fjuː/', cat:'care', def:'A time after which young guests must be back in their cabin.', short:'Time young guests must return' },
  { word:'Guest comment card', level:1, th:'บัตรแสดงความคิดเห็น', phon:'/gest ˈkɒm.ent kɑːd/', cat:'care', def:'A short form guests use to give feedback.', short:'Form for guest feedback' },
];

/* ---------- PRONUNCIATION ---------- */
const CRUISE_PRON = [
  { word:'Embarkation', th:'การขึ้นเรือ', phon:'/ˌem.bɑːˈkeɪ.ʃən/', syll:['em','bar','ka','tion'], stress:2, example:'Embarkation begins at one o\u2019clock this afternoon.' },
  { word:'Disembarkation', th:'การลงจากเรือ', phon:'/ˌdɪs.em.bɑːˈkeɪ.ʃən/', syll:['dis','em','bar','ka','tion'], stress:3, example:'Disembarkation will start at seven tomorrow morning.' },
  { word:'Muster station', th:'จุดรวมพลฉุกเฉิน', phon:'/ˈmʌs.tə ˈsteɪ.ʃən/', syll:['mus','ter','sta','tion'], stress:0, example:'Your muster station is printed on your cruise card.' },
  { word:'Itinerary', th:'กำหนดการเดินเรือ', phon:'/aɪˈtɪn.ər.ər.i/', syll:['i','tin','e','ra','ry'], stress:1, example:'Tomorrow\u2019s itinerary includes a full day at sea.' },
  { word:'Starboard', th:'กราบขวาของเรือ', phon:'/ˈstɑː.bəd/', syll:['star','board'], stress:0, example:'The island will appear on the starboard side.' },
  { word:'Gangway', th:'สะพานขึ้นลงเรือ', phon:'/ˈgæŋ.weɪ/', syll:['gang','way'], stress:0, example:'Please use the forward gangway to go ashore.' },
  { word:'Gratuity', th:'ค่าทิปบริการ', phon:'/grəˈtʃuː.ə.ti/', syll:['gra','tu','i','ty'], stress:1, example:'A daily gratuity is added to your onboard account.' },
  { word:'Buffet', th:'บุฟเฟ่ต์', phon:'/ˈbʊf.eɪ/', syll:['buf','fet'], stress:0, example:'The buffet on the Lido deck is open until midnight.' },
  { word:'Maître d\u2019', th:'หัวหน้าพนักงานต้อนรับ', phon:'/ˌmeɪ.trəˈdiː/', syll:['mai','tre','d'], stress:2, example:'Please speak to the maître d\u2019 about changing your table.' },
  { word:'Tender boat', th:'เรือเล็กรับส่งขึ้นฝั่ง', phon:'/ˈten.də bəʊt/', syll:['ten','der','boat'], stress:0, example:'A tender boat will take you ashore every twenty minutes.' },
  { word:'Amenities', th:'ของใช้ในห้องพัก', phon:'/əˈmen.ɪ.tiz/', syll:['a','men','i','ties'], stress:1, example:'I\u2019ll bring fresh amenities to your stateroom.' },
  { word:'Accessibility', th:'การเข้าถึงสำหรับทุกคน', phon:'/əkˌses.əˈbɪl.ə.ti/', syll:['ac','ces','si','bil','i','ty'], stress:3, example:'The lift has full wheelchair accessibility.' },
];

/* ---------- PHRASES ---------- */
const CRUISE_PHRASES = [
  { id:'everyday', en:'Everyday courtesies', th:'คำสุภาพที่ใช้ทุกวัน', items:[
    { level:1, text:'Good morning, and welcome aboard.', th:'สวัสดีตอนเช้าค่ะ ยินดีต้อนรับขึ้นเรือ', note:'The greeting you will use most.' },
    { level:1, text:'Certainly \u2014 one moment, please.', th:'ได้ค่ะ ขอเวลาสักครู่นะคะ', note:'Buys a moment politely.' },
    { level:1, text:'Thank you for waiting.', th:'ขอบคุณที่รอนะคะ', note:'Say it even after a short wait.' },
    { level:1, text:'It\u2019s my pleasure.', th:'เป็นความยินดีของดิฉันค่ะ', note:'A gracious reply to thanks.' },
    { level:2, text:'Excuse me, may I just pass? Thank you.', th:'ขออนุญาตเดินผ่านนะคะ ขอบคุณค่ะ', note:'Corridors on a ship are narrow.' },
    { level:2, text:'Is there anything else I can help you with?', th:'มีอะไรให้ดิฉันช่วยอีกไหมคะ', note:'Closes any interaction well.' },
    { level:1, text:'Enjoy the rest of your day.', th:'ขอให้สนุกกับช่วงเวลาที่เหลือของวันนะคะ', note:'A warm everyday farewell.' },
  ]},
  { id:'embark', en:'Welcoming guests aboard', th:'การต้อนรับขึ้นเรือ', items:[
    { level:2, text:'Welcome aboard. May I see your boarding pass and cruise card?', th:'ยินดีต้อนรับขึ้นเรือค่ะ ขอดูบัตรขึ้นเรือและบัตรประจำตัวหน่อยนะคะ', note:'The standard embarkation greeting.' },
    { level:2, text:'Your stateroom is on deck nine, midship. Shall I show you the way?', th:'ห้องพักของคุณอยู่ชั้นเก้า กลางลำเรือค่ะ ให้ดิฉันพาไปไหมคะ', note:'Give the deck and location together.' },
    { level:2, text:'Your luggage will be delivered to your cabin within a few hours.', th:'กระเป๋าของคุณจะถูกส่งไปที่ห้องพักภายในไม่กี่ชั่วโมงค่ะ', note:'Answers the most common arrival worry.' },
    { level:3, text:'The muster drill is compulsory and takes about fifteen minutes.', th:'การซ้อมรวมพลฉุกเฉินเป็นข้อบังคับ ใช้เวลาประมาณสิบห้านาทีค่ะ', note:'State it as a requirement, kindly.' },
    { level:2, text:'Your muster station is printed on the back of your cruise card.', th:'จุดรวมพลของคุณระบุอยู่ด้านหลังบัตรประจำตัวค่ะ', note:'Point to the card as you say it.' },
    { level:1, text:'The buffet on the Lido deck is open now, if you\u2019d like lunch.', th:'บุฟเฟ่ต์ที่ดาดฟ้าสระว่ายน้ำเปิดแล้วค่ะ หากต้องการรับประทานอาหารกลางวัน', note:'Useful while cabins are still being prepared.' },
  ]},
  { id:'cabin', en:'Cabin & housekeeping', th:'ห้องพักและงานแม่บ้าน', items:[
    { level:1, text:'Good morning, housekeeping. May I service your stateroom?', th:'สวัสดีตอนเช้าค่ะ แผนกแม่บ้าน ขออนุญาตทำความสะอาดห้องได้ไหมคะ', note:'Always knock and announce yourself.' },
    { level:2, text:'I\u2019ll come back later if now isn\u2019t convenient.', th:'หากตอนนี้ไม่สะดวก ดิฉันจะกลับมาอีกครั้งนะคะ', note:'Never push past a guest\u2019s timing.' },
    { level:2, text:'Would you like your bed made up as one large bed or two singles?', th:'ต้องการจัดเตียงเป็นเตียงใหญ่หนึ่งเตียง หรือเตียงเดี่ยวสองเตียงคะ', note:'Ask on the first day.' },
    { level:2, text:'I\u2019ve left fresh towels and amenities in the bathroom.', th:'ดิฉันเปลี่ยนผ้าเช็ดตัวและของใช้ในห้องน้ำใหม่ให้แล้วค่ะ', note:'Tell the guest what you did.' },
    { level:3, text:'I\u2019ll return this evening for turndown service, at around eight.', th:'ดิฉันจะกลับมาจัดเตียงตอนเย็นประมาณแปดโมงนะคะ', note:'Sets a clear expectation.' },
    { level:2, text:'If you need extra pillows or blankets, just let me know.', th:'หากต้องการหมอนหรือผ้าห่มเพิ่ม บอกดิฉันได้เลยนะคะ', note:'Offer before the guest has to ask.' },
  ]},
  { id:'dining', en:'Restaurant service', th:'บริการห้องอาหาร', items:[
    { level:2, text:'Good evening. Do you have a reservation, or is it a table for two?', th:'สวัสดีตอนเย็นค่ะ ท่านจองโต๊ะไว้หรือไม่ หรือรับโต๊ะสำหรับสองท่านคะ', note:'Covers both cases in one question.' },
    { level:2, text:'May I seat you by the window this evening?', th:'ขอเชิญนั่งโต๊ะริมหน้าต่างเย็นนี้ไหมคะ', note:'Offering, not assigning.' },
    { level:3, text:'Do you have any allergies or dietary requirements I should tell the galley?', th:'ท่านมีอาการแพ้อาหารหรือข้อจำกัดด้านอาหารที่ควรแจ้งครัวไหมคะ', note:'An essential safety question.' },
    { level:2, text:'Are you ready to order, or would you like a few more minutes?', th:'พร้อมสั่งอาหารหรือยังคะ หรือขอเวลาอีกสักครู่', note:'Never rush a table.' },
    { level:2, text:'May I clear these plates for you?', th:'ขออนุญาตเก็บจานได้ไหมคะ', note:'Ask before removing anything.' },
    { level:3, text:'The speciality restaurant carries an additional charge \u2014 shall I explain?', th:'ห้องอาหารพิเศษมีค่าบริการเพิ่มค่ะ ให้ดิฉันอธิบายไหมคะ', note:'Be clear about extra charges early.' },
    { level:1, text:'Enjoy your meal.', th:'ขอให้อร่อยนะคะ', note:'Say it as you step away.' },
  ]},
  { id:'bar', en:'Bar & drinks service', th:'บริการบาร์และเครื่องดื่ม', items:[
    { level:1, text:'What can I get you this evening?', th:'เย็นนี้รับเครื่องดื่มอะไรดีคะ', note:'A friendly, open opener.' },
    { level:2, text:'Would you like that with or without alcohol?', th:'รับแบบมีแอลกอฮอล์หรือไม่มีคะ', note:'Ask rather than assume.' },
    { level:2, text:'May I see your cruise card, please?', th:'ขอดูบัตรประจำตัวผู้โดยสารหน่อยนะคะ', note:'Needed for every charge.' },
    { level:3, text:'That drink is included in your beverage package.', th:'เครื่องดื่มนี้รวมอยู่ในแพ็กเกจของคุณแล้วค่ะ', note:'Good news, so say it clearly.' },
    { level:3, text:'I\u2019m afraid that one falls outside your package \u2014 there\u2019s a small extra charge.', th:'ขออภัยค่ะ รายการนี้ไม่รวมในแพ็กเกจ มีค่าใช้จ่ายเพิ่มเล็กน้อย', note:'Say it before serving, never after.' },
    { level:2, text:'Last call is in ten minutes, if you\u2019d like another.', th:'อีกสิบนาทีจะปิดรับออร์เดอร์ค่ะ หากต้องการสั่งเพิ่ม', note:'A courtesy warning before closing.' },
  ]},
  { id:'shipinfo', en:'Questions about the ship', th:'คำถามเกี่ยวกับเรือ', items:[
    { level:1, text:'The theatre is on deck five, forward. Take the lift and turn left.', th:'โรงละครอยู่ชั้นห้า ด้านหัวเรือค่ะ ขึ้นลิฟต์แล้วเลี้ยวซ้าย', note:'Give deck, direction, then the turn.' },
    { level:2, text:'There\u2019s a deck plan by every lift \u2014 shall I mark it for you?', th:'มีแผนผังชั้นเรืออยู่ข้างลิฟต์ทุกตัวค่ะ ให้ดิฉันทำเครื่องหมายให้ไหมคะ', note:'Better than a long verbal direction.' },
    { level:2, text:'The pool is on the Lido deck, one floor above us.', th:'สระว่ายน้ำอยู่ที่ดาดฟ้าไลโด ชั้นเหนือขึ้นไปหนึ่งชั้นค่ะ', note:'Relative directions are easier to follow.' },
    { level:3, text:'That area is restricted to crew, but I can take your request there myself.', th:'บริเวณนั้นสงวนสำหรับลูกเรือค่ะ แต่ดิฉันช่วยนำเรื่องไปแจ้งให้ได้', note:'Refuse the access, not the request.' },
    { level:2, text:'Today\u2019s programme is delivered to your cabin each evening.', th:'กำหนดการของแต่ละวันจะส่งไปที่ห้องพักทุกเย็นค่ะ', note:'Points guests to the answer next time.' },
    { level:2, text:'We\u2019ll be at sea all day tomorrow, and reach port on Thursday morning.', th:'พรุ่งนี้เราจะแล่นอยู่กลางทะเลทั้งวัน และถึงท่าเรือเช้าวันพฤหัสบดีค่ะ', note:'Answers the most-asked question aboard.' },
  ]},
  { id:'safety', en:'Safety & drills', th:'ความปลอดภัยและการซ้อม', items:[
    { level:3, text:'This is the muster drill. Please make your way to your muster station now.', th:'นี่คือการซ้อมรวมพลฉุกเฉินค่ะ กรุณาไปยังจุดรวมพลของท่านตอนนี้', note:'Clear, calm and directive.' },
    { level:2, text:'Please take the stairs, not the lift, during the drill.', th:'ระหว่างการซ้อม กรุณาใช้บันไดแทนลิฟต์นะคะ', note:'A rule guests forget every cruise.' },
    { level:2, text:'Your life jacket is in the wardrobe in your cabin.', th:'เสื้อชูชีพอยู่ในตู้เสื้อผ้าในห้องพักของท่านค่ะ', note:'Asked constantly at the drill.' },
    { level:3, text:'Seven short blasts and one long blast means go to your muster station.', th:'สัญญาณสั้นเจ็ดครั้งและยาวหนึ่งครั้ง หมายถึงให้ไปที่จุดรวมพลค่ะ', note:'Every crew member must know this.' },
    { level:2, text:'Please keep this door closed \u2014 it\u2019s a fire door.', th:'กรุณาปิดประตูนี้ไว้นะคะ เป็นประตูกันไฟค่ะ', note:'Give the reason, so it is not just a rule.' },
    { level:2, text:'May I ask you to use the hand sanitiser before entering?', th:'ขอความร่วมมือใช้เจลล้างมือก่อนเข้าไปนะคะ', note:'Standard at every dining entrance.' },
  ]},
  { id:'excursion', en:'Ports & excursions', th:'ท่าเรือและทัวร์ชายฝั่ง', items:[
    { level:2, text:'All aboard time is four thirty this afternoon, please don\u2019t be late.', th:'เวลากลับขึ้นเรือคือสี่โมงครึ่งบ่ายนี้ กรุณาอย่ามาสายนะคะ', note:'Repeat the time twice; it matters most.' },
    { level:3, text:'The ship cannot dock here, so a tender boat will take you ashore.', th:'เรือไม่สามารถเทียบท่าที่นี่ได้ จะมีเรือเล็กรับส่งขึ้นฝั่งค่ะ', note:'Explains an unfamiliar arrangement.' },
    { level:2, text:'Your tour meets at the gangway fifteen minutes beforehand.', th:'ทัวร์ของท่านนัดพบที่สะพานขึ้นลงเรือก่อนเวลาสิบห้านาทีค่ะ', note:'Give place and time together.' },
    { level:2, text:'Please take your cruise card and some local currency ashore.', th:'กรุณานำบัตรประจำตัวและเงินสกุลท้องถิ่นติดตัวไปด้วยนะคะ', note:'Prevents the two most common problems.' },
    { level:3, text:'Shore excursions can be booked at the desk or on the cabin television.', th:'ทัวร์ชายฝั่งจองได้ที่เคาน์เตอร์ หรือผ่านโทรทัศน์ในห้องพักค่ะ', note:'Offers two easy routes.' },
    { level:2, text:'Do remember the ship runs on ship\u2019s time, not local time.', th:'อย่าลืมว่าเรือใช้เวลาของเรือ ไม่ใช่เวลาท้องถิ่นนะคะ', note:'This one saves guests from missing the ship.' },
  ]},
  { id:'complaints', en:'Handling complaints', th:'การจัดการข้อร้องเรียน', items:[
    { level:2, text:'I\u2019m very sorry \u2014 let me see what I can do to put this right.', th:'ดิฉันขออภัยอย่างยิ่งค่ะ ขอดูว่าจะแก้ไขให้ได้อย่างไร', note:'Empathy first, always.' },
    { level:2, text:'Thank you for telling me. May I take your cabin number?', th:'ขอบคุณที่แจ้งนะคะ ขอทราบหมายเลขห้องพักได้ไหมคะ', note:'Lets you follow up properly.' },
    { level:3, text:'I completely understand, and I\u2019ll raise this with my department head now.', th:'ดิฉันเข้าใจอย่างยิ่งค่ะ และจะแจ้งหัวหน้าแผนกทันที', note:'Shows the guest it will move.' },
    { level:3, text:'As an apology, may I offer you dinner in our speciality restaurant?', th:'เพื่อเป็นการขอโทษ ขอเชิญท่านรับประทานอาหารเย็นที่ห้องอาหารพิเศษไหมคะ', note:'A concrete gesture beats more words.' },
    { level:2, text:'Would you prefer to wait here, or shall I come to your cabin?', th:'ท่านสะดวกรอที่นี่ หรือให้ดิฉันไปที่ห้องพักคะ', note:'Gives the guest control.' },
    { level:3, text:'I\u2019ll follow this up personally and let you know by this evening.', th:'ดิฉันจะติดตามเรื่องนี้ด้วยตัวเอง และแจ้งให้ทราบภายในเย็นนี้ค่ะ', note:'Promise a time, then keep it.' },
  ]},
  { id:'care', en:'Special care & assistance', th:'การดูแลกรณีพิเศษ', items:[
    { level:2, text:'Are you feeling unwell? The medical centre is on deck two.', th:'ท่านรู้สึกไม่สบายหรือเปล่าคะ ศูนย์การแพทย์อยู่ชั้นสองค่ะ', note:'Common on the first day at sea.' },
    { level:2, text:'Ginger tea and crackers can help with seasickness \u2014 shall I bring some?', th:'ชาขิงและแครกเกอร์ช่วยบรรเทาอาการเมาเรือได้ค่ะ ให้ดิฉันนำมาให้ไหมคะ', note:'A practical kindness guests remember.' },
    { level:2, text:'Let me walk with you \u2014 the deck can move a little in this weather.', th:'ให้ดิฉันเดินไปด้วยนะคะ ดาดฟ้าอาจโยกเล็กน้อยในสภาพอากาศนี้', note:'Offer, do not wait to be asked.' },
    { level:3, text:'There\u2019s step-free access to the theatre by the forward lift.', th:'มีทางเข้าโรงละครแบบไม่มีขั้นบันได โดยใช้ลิฟต์ด้านหัวเรือค่ะ', note:'Know your accessible routes.' },
    { level:2, text:'We can arrange priority boarding for you at the next port.', th:'เราสามารถจัดสิทธิ์ขึ้นเรือก่อนให้ท่านที่ท่าเรือถัดไปได้ค่ะ', note:'Solves a problem before it repeats.' },
    { level:2, text:'If you feel unsteady at any point, please tell a crew member.', th:'หากรู้สึกทรงตัวไม่มั่นคงตอนไหน กรุณาแจ้งลูกเรือนะคะ', note:'Safety phrasing that does not alarm.' },
  ]},
  { id:'selling', en:'Offering extras politely', th:'การแนะนำบริการเสริม', items:[
    { level:2, text:'Would you like to add a beverage package? Many guests find it good value.', th:'สนใจเพิ่มแพ็กเกจเครื่องดื่มไหมคะ ผู้โดยสารหลายท่านว่าคุ้มค่า', note:'Social proof, not pressure.' },
    { level:2, text:'No problem at all if you\u2019d rather not.', th:'ไม่เป็นไรเลยค่ะ หากท่านไม่สะดวก', note:'Always give an easy way out.' },
    { level:3, text:'If you\u2019re sailing with us again, our loyalty tier brings extra benefits.', th:'หากท่านเดินทางกับเราอีกครั้ง ระดับสมาชิกของเรามีสิทธิประโยชน์เพิ่มค่ะ', note:'Frames the offer as a reward.' },
    { level:2, text:'Tonight\u2019s speciality restaurant still has a table at eight.', th:'ห้องอาหารพิเศษคืนนี้ยังมีโต๊ะว่างเวลาแปดโมงค่ะ', note:'A gentle reason to decide now.' },
    { level:3, text:'This excursion sells out quickly \u2014 shall I hold two places for you?', th:'ทัวร์นี้เต็มเร็วค่ะ ให้ดิฉันจองไว้สองที่ไหมคะ', note:'Urgency that is actually true.' },
    { level:2, text:'You can add it to your onboard account, if that\u2019s easier.', th:'สามารถเพิ่มเข้าบัญชีบนเรือได้ค่ะ หากสะดวกกว่า', note:'Removes friction from the decision.' },
  ]},
  { id:'crewtalk', en:'Talking with your team', th:'การสื่อสารกับทีมงาน', items:[
    { level:2, text:'Just to hand over: cabin 9042 has asked for extra pillows.', th:'ขอส่งต่อข้อมูลนะ ห้อง 9042 ขอหมอนเพิ่ม', note:'Clean, specific handover.' },
    { level:2, text:'Could you cover my section? I\u2019m running a few minutes behind.', th:'ช่วยดูแลโซนของฉันแทนได้ไหม ฉันช้าไปสองสามนาที', note:'Ask clearly and early.' },
    { level:2, text:'I\u2019ve logged it in the handover book for the next watch.', th:'ฉันบันทึกไว้ในสมุดส่งงานให้เวรถัดไปแล้ว', note:'Written records prevent repeats.' },
    { level:3, text:'Would you mind if I escalated this to the department head?', th:'ขอส่งเรื่องนี้ให้หัวหน้าแผนกได้ไหม', note:'Knowing when to escalate.' },
    { level:2, text:'We\u2019re low on towels \u2014 could someone restock the trolley?', th:'ผ้าเช็ดตัวเหลือน้อยแล้ว ใครช่วยเติมในรถเข็นได้ไหม', note:'Flag supply problems early.' },
    { level:1, text:'Thanks for stepping in earlier \u2014 that really helped.', th:'ขอบคุณที่มาช่วยเมื่อกี้นะ ช่วยได้มากเลย', note:'Recognise support from colleagues.' },
  ]},
  { id:'farewell', en:'Disembarkation & farewell', th:'การลงจากเรือและกล่าวลา', items:[
    { level:3, text:'Disembarkation begins at seven. Your luggage tags show your group colour.', th:'การลงจากเรือเริ่มเจ็ดโมงค่ะ ป้ายกระเป๋าจะระบุสีกลุ่มของท่าน', note:'Two facts guests need together.' },
    { level:2, text:'Please leave your suitcases outside your cabin before ten tonight.', th:'กรุณาวางกระเป๋าเดินทางไว้หน้าห้องพักก่อนสี่ทุ่มคืนนี้นะคะ', note:'Say the deadline plainly.' },
    { level:2, text:'Your final statement will be delivered to your cabin overnight.', th:'ใบสรุปค่าใช้จ่ายจะส่งไปที่ห้องพักในคืนนี้ค่ะ', note:'Heads off billing questions.' },
    { level:2, text:'We\u2019d love to hear how your cruise was \u2014 there\u2019s a comment card in your folder.', th:'เราอยากทราบความคิดเห็นเกี่ยวกับการเดินทางของท่านค่ะ มีบัตรแสดงความคิดเห็นในแฟ้ม', note:'Invites feedback without pressure.' },
    { level:1, text:'Thank you for sailing with us. Safe travels home.', th:'ขอบคุณที่ร่วมเดินทางกับเรานะคะ เดินทางกลับปลอดภัยค่ะ', note:'The last thing a guest hears.' },
    { level:2, text:'It\u2019s been a pleasure looking after you this week.', th:'เป็นเกียรติที่ได้ดูแลท่านในสัปดาห์นี้ค่ะ', note:'Personal and sincere.' },
  ]},
];

/* ---------- SAY THIS, NOT THAT ---------- */
const CRUISE_SAYTHIS = [
  { scenario:'Guest asks where something is', dont:'It\u2019s upstairs.', dontTh:'อยู่ชั้นบน',
    doo:'It\u2019s on deck nine, just above us \u2014 shall I show you on the deck plan?',
    dooTh:'อยู่ชั้นเก้า เหนือขึ้นไปหนึ่งชั้นค่ะ ให้ดิฉันชี้ในแผนผังให้ไหมคะ',
    why:'On a ship "upstairs" is meaningless. Always give the deck number and a direction.' },
  { scenario:'Guest wants to skip the muster drill', dont:'You have to go, it\u2019s the rule.', dontTh:'คุณต้องไป มันเป็นกฎ',
    doo:'It\u2019s required by maritime law and takes only fifteen minutes \u2014 it keeps everyone safe.',
    dooTh:'เป็นข้อบังคับตามกฎหมายทางทะเล ใช้เวลาเพียงสิบห้านาที เพื่อความปลอดภัยของทุกคนค่ะ',
    why:'Explaining the reason gets cooperation; citing "the rule" invites an argument.' },
  { scenario:'Guest is late back from shore', dont:'You\u2019re late. The ship almost left.', dontTh:'คุณมาสาย เรือเกือบออกแล้ว',
    doo:'I\u2019m glad you made it back safely. Do check the all aboard time for tomorrow.',
    dooTh:'ดีใจที่ท่านกลับมาถึงอย่างปลอดภัยค่ะ พรุ่งนี้อย่าลืมตรวจเวลากลับขึ้นเรือนะคะ',
    why:'Relief plus a forward-looking reminder works better than blame.' },
  { scenario:'Guest asks for a restricted area', dont:'You can\u2019t go there.', dontTh:'คุณไปที่นั่นไม่ได้',
    doo:'That area is crew only, but I\u2019d be glad to take your request there myself.',
    dooTh:'บริเวณนั้นสงวนสำหรับลูกเรือค่ะ แต่ดิฉันยินดีนำเรื่องไปแจ้งให้',
    why:'Refuse the access without refusing the person.' },
  { scenario:'Drink is outside the package', dont:'That\u2019s not included. It costs extra.', dontTh:'อันนั้นไม่รวม ต้องจ่ายเพิ่ม',
    doo:'That one falls just outside your package \u2014 there\u2019s a small extra charge. Would you still like it?',
    dooTh:'รายการนี้ไม่รวมในแพ็กเกจค่ะ มีค่าใช้จ่ายเพิ่มเล็กน้อย ยังต้องการรับไหมคะ',
    why:'Tell the guest before you pour, and let them choose. Never surprise them on the bill.' },
  { scenario:'Guest feels seasick', dont:'Everyone gets seasick, it\u2019s normal.', dontTh:'ทุกคนก็เมาเรือ เป็นเรื่องปกติ',
    doo:'I\u2019m sorry you\u2019re feeling unwell. Ginger tea helps \u2014 and the medical centre is on deck two.',
    dooTh:'เสียใจที่ท่านรู้สึกไม่สบายค่ะ ชาขิงช่วยได้ และศูนย์การแพทย์อยู่ชั้นสองค่ะ',
    why:'Sympathy plus two practical options, rather than dismissing the feeling.' },
  { scenario:'Cabin is not ready yet', dont:'Your cabin is not ready. Wait.', dontTh:'ห้องยังไม่พร้อม รอไปก่อน',
    doo:'Your stateroom will be ready by two. Until then, the buffet on deck eleven is open.',
    dooTh:'ห้องพักของท่านจะพร้อมภายในบ่ายสองค่ะ ระหว่างนี้บุฟเฟ่ต์ชั้นสิบเอ็ดเปิดให้บริการ',
    why:'Give a time and something to do in the meantime.' },
  { scenario:'Guest complains about noise', dont:'There\u2019s nothing I can do about it.', dontTh:'ฉันทำอะไรไม่ได้',
    doo:'I\u2019m sorry \u2014 let me take your cabin number and speak with my supervisor about moving you.',
    dooTh:'ขออภัยค่ะ ขอทราบหมายเลขห้องพัก แล้วดิฉันจะปรึกษาหัวหน้าเรื่องการย้ายห้องให้',
    why:'Never close the conversation. Offer the next step, even if you cannot fix it yourself.' },
  { scenario:'Guest asks a question you can\u2019t answer', dont:'I don\u2019t know.', dontTh:'ไม่รู้',
    doo:'That\u2019s a good question \u2014 let me find out and come back to you within the hour.',
    dooTh:'เป็นคำถามที่ดีค่ะ ขอไปหาคำตอบแล้วกลับมาแจ้งภายในหนึ่งชั่วโมง',
    why:'Promising a time turns "I don\u2019t know" into good service.' },
  { scenario:'Guest is at the wrong seating time', dont:'You\u2019re at the wrong sitting.', dontTh:'คุณมาผิดรอบ',
    doo:'Your table is booked for the later sitting \u2014 but let me see what I can do for you now.',
    dooTh:'โต๊ะของท่านจองไว้รอบหลังค่ะ แต่ขอดูว่าจะจัดให้ตอนนี้ได้ไหมนะคะ',
    why:'Correct the fact, then look for a solution rather than leaving them stranded.' },
  { scenario:'A colleague made the mistake', dont:'That wasn\u2019t me, it was the night steward.', dontTh:'ไม่ใช่ฉัน เป็นพนักงานกะกลางคืน',
    doo:'I\u2019m sorry that happened \u2014 let me put it right for you now.',
    dooTh:'ขออภัยที่เกิดเรื่องนี้ขึ้นค่ะ ขอแก้ไขให้เลยนะคะ',
    why:'Guests experience one ship, not separate shifts. Deflecting blame damages that trust.' },
  { scenario:'Guest asks about gratuities', dont:'You have to pay it, it\u2019s automatic.', dontTh:'คุณต้องจ่าย มันอัตโนมัติ',
    doo:'A daily service gratuity is added to your onboard account \u2014 I can show you the details.',
    dooTh:'มีค่าบริการรายวันเพิ่มเข้าบัญชีบนเรือค่ะ ดิฉันแสดงรายละเอียดให้ดูได้',
    why:'Explain calmly and offer the documentation. Money questions need clarity, not defensiveness.' },
  { scenario:'Guest blocks a fire door', dont:'Don\u2019t leave that open.', dontTh:'อย่าเปิดทิ้งไว้',
    doo:'May I close this for you? It\u2019s a fire door, so it needs to stay shut.',
    dooTh:'ขออนุญาตปิดประตูนี้นะคะ เป็นประตูกันไฟ จึงต้องปิดไว้ค่ะ',
    why:'Do it yourself and give the reason, rather than issuing an instruction.' },
  { scenario:'Guest wants a photo in a crew area', dont:'No photos here.', dontTh:'ห้ามถ่ายรูปที่นี่',
    doo:'I\u2019m afraid we can\u2019t take photographs in this area \u2014 but the promenade deck has a wonderful view.',
    dooTh:'บริเวณนี้ไม่อนุญาตให้ถ่ายภาพค่ะ แต่ดาดฟ้าเดินเล่นมีวิวสวยมากนะคะ',
    why:'Pair the refusal with a better alternative.' },
];

/* ---------- ACTIVITY BANKS ---------- */
const CRUISE_MC_BANK = [
  { q:'What is a \u201cmuster station\u201d?', options:['A crew dining room','The place a guest goes in an emergency','A cabin with a balcony','The ship\u2019s kitchen'], correct:1,
    hit:'Correct \u2014 and it is printed on the guest\u2019s cruise card.', miss:'A muster station is the place a guest must go in an emergency.' },
  { q:'\u201cStarboard\u201d means:', options:['The front of the ship','The right side when facing forward','The back of the ship','The top deck'], correct:1,
    hit:'Right \u2014 starboard is the right-hand side facing forward.', miss:'Starboard is the right-hand side of the ship when facing forward.' },
  { q:'A guest asks where the theatre is. Best answer?', options:['It\u2019s upstairs.','It\u2019s on deck five, forward \u2014 take the lift and turn left.','Somewhere on five.','Ask someone else.'], correct:1,
    hit:'Exactly \u2014 deck number, direction, then the turn.', miss:'On a ship, always give the deck number and a direction. \u201cUpstairs\u201d means nothing.' },
  { q:'\u201cAll aboard time\u201d is:', options:['When the buffet opens','The time every guest must be back on the ship','The start of the muster drill','When the bar closes'], correct:1,
    hit:'Correct \u2014 and it is worth repeating twice to guests.', miss:'All aboard time is the deadline for guests to be back on the ship.' },
  { q:'What does a \u201ctender boat\u201d do?', options:['Delivers luggage','Carries guests ashore where the ship cannot dock','Tows the ship','Collects rubbish'], correct:1,
    hit:'Right \u2014 used when there is no berth for the ship.', miss:'A tender boat carries guests ashore where the ship cannot dock.' },
  { q:'The general emergency alarm is:', options:['One long blast','Seven short blasts and one long blast','Three short blasts','A continuous bell'], correct:1,
    hit:'Correct \u2014 every crew member must know this signal.', miss:'It is seven short blasts followed by one long blast.' },
  { q:'A guest\u2019s drink is not in their package. What do you say?', options:['That\u2019s not included.','That one falls outside your package \u2014 there\u2019s a small extra charge. Would you still like it?','You have to pay.','I\u2019ll charge you anyway.'], correct:1,
    hit:'Right \u2014 tell them before you pour, and let them choose.', miss:'Explain the extra charge before serving, and let the guest decide.' },
  { q:'\u201cTurndown service\u201d means:', options:['Refusing a guest request','Preparing the bed and cabin in the evening','Turning off the air conditioning','Lowering the price'], correct:1,
    hit:'Correct \u2014 the evening cabin visit.', miss:'Turndown service is the evening visit to prepare the bed and tidy the cabin.' },
  { q:'A guest feels seasick. Best response?', options:['Everyone gets seasick.','I\u2019m sorry you feel unwell \u2014 ginger tea helps, and the medical centre is on deck two.','Go and lie down.','It will pass.'], correct:1,
    hit:'Exactly \u2014 sympathy plus two practical options.', miss:'Show sympathy and offer something practical, plus the medical centre.' },
  { q:'What is a guest\u2019s \u201conboard account\u201d?', options:['Their loyalty number','The running bill of everything they charge','Their cabin number','Their booking reference'], correct:1,
    hit:'Correct \u2014 charged with the cruise card.', miss:'The onboard account is the running bill of a guest\u2019s charges.' },
  { q:'A guest asks to enter a crew-only area. Best reply?', options:['You can\u2019t go there.','That area is crew only, but I\u2019d be glad to take your request there myself.','It\u2019s forbidden.','Nobody is allowed.'], correct:1,
    hit:'Right \u2014 refuse the access, not the person.', miss:'Refuse the access but offer to help with what they actually needed.' },
  { q:'\u201cDisembarkation\u201d is:', options:['Boarding the ship','Leaving the ship at the end of a cruise','A safety drill','A shore excursion'], correct:1,
    hit:'Correct \u2014 the opposite of embarkation.', miss:'Disembarkation is the process of leaving the ship at the end of a cruise.' },
  { q:'Why must a fire door stay closed?', options:['To keep the corridor quiet','To hold back fire and smoke','To save electricity','To stop guests entering'], correct:1,
    hit:'Right \u2014 and always explain that reason to guests.', miss:'A fire door holds back fire and smoke, so it must stay shut.' },
  { q:'Best way to handle a complaint you cannot fix yourself?', options:['There\u2019s nothing I can do.','I\u2019m sorry \u2014 let me take your cabin number and speak with my supervisor.','Complain to guest services.','That\u2019s not my department.'], correct:1,
    hit:'Exactly \u2014 always offer the next step.', miss:'Never close the conversation. Take details and escalate.' },
  { q:'\u201cShip\u2019s time\u201d matters because:', options:['It is always GMT','It may differ from local time ashore','It changes every hour','Only the crew use it' ], correct:1,
    hit:'Correct \u2014 this is how guests miss the ship.', miss:'Ship\u2019s time can differ from local time, so all aboard time follows the ship.' },
  { q:'A \u201cdietary requirement\u201d is:', options:['A guest\u2019s favourite dish','A food a guest must avoid, for health or belief','A menu price','A table booking'], correct:1,
    hit:'Right \u2014 and the galley must be told.', miss:'A dietary requirement is food a guest must avoid, for health or belief.' },
  { q:'Guest\u2019s cabin is not ready. Best answer?', options:['Your cabin is not ready. Wait.','Your stateroom will be ready by two \u2014 until then the buffet on deck eleven is open.','Come back later.','I don\u2019t know when.'], correct:1,
    hit:'Perfect \u2014 a time plus something to do meanwhile.', miss:'Give a specific time and suggest something to do in the meantime.' },
  { q:'\u201cGratuity\u201d means:', options:['A discount','A service tip','A refund','A free upgrade'], correct:1,
    hit:'Correct \u2014 often added daily to the onboard account.', miss:'A gratuity is a service tip, often added to the onboard account.' },
  { q:'Where is a guest\u2019s life jacket normally kept?', options:['At the muster station','In the wardrobe in their cabin','At guest services','On the lifeboat'], correct:1,
    hit:'Right \u2014 guests ask this at every drill.', miss:'Life jackets are normally in the wardrobe in the guest\u2019s cabin.' },
  { q:'During the muster drill, guests should:', options:['Use the lifts','Use the stairs','Stay in their cabins','Wait at the bar'], correct:1,
    hit:'Correct \u2014 stairs only during a drill.', miss:'Guests must use the stairs, not the lifts, during a drill.' },
  { q:'A guest returns late from shore. Best response?', options:['You\u2019re late, the ship almost left.','I\u2019m glad you made it back safely \u2014 do check tomorrow\u2019s all aboard time.','You should be more careful.','Next time we\u2019ll leave you.'], correct:1,
    hit:'Right \u2014 relief plus a forward-looking reminder.', miss:'Express relief, then remind them about the next all aboard time.' },
  { q:'\u201cPort of call\u201d means:', options:['The left side of the ship','A place the ship stops so guests can go ashore','The harbour office','A type of drink'], correct:1,
    hit:'Correct \u2014 note it is different from \u201cport side\u201d.', miss:'A port of call is a place the ship stops so guests can go ashore.' },
  { q:'What should a guest take ashore?', options:['Their passport only','Their cruise card and some local currency','Nothing at all','Their life jacket'], correct:1,
    hit:'Right \u2014 those two prevent most problems.', miss:'Guests need their cruise card to reboard, plus some local currency.' },
  { q:'A \u201cfolio\u201d is:', options:['A shore excursion ticket','The printed statement of a guest\u2019s onboard charges','A cabin key','The dinner menu'], correct:1,
    hit:'Correct \u2014 delivered before disembarkation.', miss:'A folio is the printed statement of a guest\u2019s onboard charges.' },
];

const CRUISE_TRUE_FALSE_BANK = [
  { statement:'The muster drill is optional if a guest has cruised before.', answer:false, why:'It is required by maritime law for every guest, on every cruise.' },
  { statement:'\u201cStarboard\u201d is the right-hand side of the ship when facing forward.', answer:true, why:'Correct \u2014 and port side is the left.' },
  { statement:'On a ship it is helpful to tell guests something is \u201cupstairs\u201d.', answer:false, why:'Always give the deck number and a direction instead.' },
  { statement:'All aboard time follows ship\u2019s time, not local time ashore.', answer:true, why:'Correct \u2014 this is exactly how guests miss the ship.' },
  { statement:'A tender boat is used when the ship cannot dock at a port.', answer:true, why:'Correct \u2014 it carries guests between ship and shore.' },
  { statement:'You should tell a guest about an extra charge after serving the drink.', answer:false, why:'Always explain the charge before serving, and let them choose.' },
  { statement:'Guests should use the lifts during a muster drill.', answer:false, why:'Stairs only. Lifts may be needed or unsafe in a real emergency.' },
  { statement:'A fire door may be propped open if the corridor is busy.', answer:false, why:'Fire doors must stay closed to hold back fire and smoke.' },
  { statement:'Turndown service happens in the evening.', answer:true, why:'Correct \u2014 the bed is prepared and the cabin tidied for the night.' },
  { statement:'\u201cEmbarkation\u201d means leaving the ship at the end of a cruise.', answer:false, why:'That is disembarkation. Embarkation is boarding.' },
  { statement:'A guest\u2019s muster station is printed on their cruise card.', answer:true, why:'Correct \u2014 point to the card when a guest asks.' },
  { statement:'It is professional to tell a guest which colleague caused a problem.', answer:false, why:'Apologise and fix it. Guests experience one ship, not separate shifts.' },
  { statement:'The general emergency alarm is seven short blasts and one long blast.', answer:true, why:'Correct \u2014 every crew member must know this.' },
  { statement:'A dietary requirement only means vegetarian food.', answer:false, why:'It covers any food a guest must avoid, for health or belief.' },
  { statement:'Ginger tea can help a guest with seasickness.', answer:true, why:'Correct \u2014 a simple, practical kindness.' },
  { statement:'Guests need their cruise card to get back on board.', answer:true, why:'Correct \u2014 remind them before they go ashore.' },
  { statement:'\u201cPort of call\u201d and \u201cport side\u201d mean the same thing.', answer:false, why:'A port of call is a stop; port side is the left of the ship.' },
  { statement:'If you cannot answer a guest\u2019s question, it is best to say only \u201cI don\u2019t know\u201d.', answer:false, why:'Offer to find out and give them a time you will return.' },
];

const CRUISE_ERROR_BANK = [
  { wrong:'It\u2019s upstairs.', options:['It\u2019s on deck nine, just above us \u2014 shall I show you the deck plan?','Somewhere up there.','Go up and look.'], correct:0,
    why:'On a ship you must give the deck number and a direction.' },
  { wrong:'You have to go to the drill, it\u2019s the rule.', options:['It\u2019s required by maritime law and takes only fifteen minutes \u2014 it keeps everyone safe.','It is compulsory.','No exceptions.'], correct:0,
    why:'Explaining the reason wins cooperation; citing the rule invites argument.' },
  { wrong:'You\u2019re late. The ship almost left.', options:['I\u2019m glad you made it back safely \u2014 do check tomorrow\u2019s all aboard time.','You should have been earlier.','Next time we leave without you.'], correct:0,
    why:'Relief plus a forward-looking reminder, not blame.' },
  { wrong:'You can\u2019t go there.', options:['That area is crew only, but I\u2019d be glad to take your request there myself.','It\u2019s not allowed.','Guests are forbidden.'], correct:0,
    why:'Refuse the access without refusing the person.' },
  { wrong:'That\u2019s not included. It costs extra.', options:['That one falls just outside your package \u2014 there\u2019s a small extra charge. Would you still like it?','You must pay more.','Not in your package.'], correct:0,
    why:'Tell the guest before you pour, and let them choose.' },
  { wrong:'Everyone gets seasick, it\u2019s normal.', options:['I\u2019m sorry you\u2019re feeling unwell \u2014 ginger tea helps, and the medical centre is on deck two.','It happens to everybody.','You\u2019ll get used to it.'], correct:0,
    why:'Sympathy plus two practical options beats dismissing the feeling.' },
  { wrong:'Your cabin is not ready. Wait.', options:['Your stateroom will be ready by two \u2014 until then the buffet on deck eleven is open.','Come back later.','Not ready yet.'], correct:0,
    why:'Give a time, and something to do in the meantime.' },
  { wrong:'There\u2019s nothing I can do about it.', options:['I\u2019m sorry \u2014 let me take your cabin number and speak with my supervisor.','That\u2019s not my department.','You\u2019ll have to accept it.'], correct:0,
    why:'Never close the conversation. Offer the next step.' },
  { wrong:'I don\u2019t know.', options:['That\u2019s a good question \u2014 let me find out and come back to you within the hour.','Nobody knows.','Ask guest services.'], correct:0,
    why:'Promising a time turns a dead end into good service.' },
  { wrong:'Don\u2019t leave that open.', options:['May I close this for you? It\u2019s a fire door, so it needs to stay shut.','Close the door.','That must be shut.'], correct:0,
    why:'Do it yourself and give the reason.' },
  { wrong:'No photos here.', options:['I\u2019m afraid we can\u2019t take photographs in this area \u2014 but the promenade deck has a wonderful view.','Photography is banned.','Put your camera away.'], correct:0,
    why:'Pair the refusal with a better alternative.' },
  { wrong:'That wasn\u2019t me, it was the night steward.', options:['I\u2019m sorry that happened \u2014 let me put it right for you now.','You should speak to him.','It wasn\u2019t my shift.'], correct:0,
    why:'Guests experience one ship. Deflecting blame breaks their trust.' },
];

const CRUISE_LISTEN_BANK = [
  { target:'Embarkation',      distractors:['Disembarkation','Accessibility','Itinerary'] },
  { target:'Disembarkation',   distractors:['Embarkation','Gratuity','Amenities'] },
  { target:'Muster station',   distractors:['Medical centre','Meeting point','Crew mess'] },
  { target:'Starboard',        distractors:['Port side','Stern','Bow'] },
  { target:'Gangway',          distractors:['Galley','Atrium','Gratuity'] },
  { target:'Gratuity',         distractors:['Folio','Upgrade','Itinerary'] },
  { target:'Tender boat',      distractors:['Lifeboat','Life jacket','Deck plan'] },
  { target:'Itinerary',        distractors:['Amenities','Accessibility','Curfew'] },
  { target:'Amenities',        distractors:['Accessibility','Gratuity','Minibar'] },
  { target:'Stateroom',        distractors:['Interior cabin','Balcony cabin','Crew mess'] },
  { target:'Buffet',           distractors:['Galley','Wine list','Last call'] },
  { target:'Seasickness',      distractors:['Special assistance','Mobility assistance','Quiet zone'] },
  { target:'Turndown service', distractors:['Linen change','Housekeeping trolley','Do not disturb sign'] },
  { target:'Port of call',     distractors:['Port side','Sea day','Shore leave'] },
  { target:'Accessibility',    distractors:['Amenities','Priority boarding','Special assistance'] },
  { target:'Cruise card',      distractors:['Cabin key card','Boarding pass','Allergy card'] },
];

const CRUISE_BUILDER_BANK = [
  { th:'ยินดีต้อนรับขึ้นเรือค่ะ',                          sentence:'Welcome aboard.' },
  { th:'ขอดูบัตรประจำตัวผู้โดยสารหน่อยนะคะ',              sentence:'May I see your cruise card?' },
  { th:'ห้องพักของคุณอยู่ชั้นเก้าค่ะ',                      sentence:'Your stateroom is on deck nine.' },
  { th:'จุดรวมพลอยู่ด้านหลังบัตรของท่าน',                   sentence:'Your muster station is on your card.' },
  { th:'เวลากลับขึ้นเรือคือสี่โมงครึ่ง',                     sentence:'All aboard time is four thirty.' },
  { th:'กรุณาใช้บันไดระหว่างการซ้อม',                      sentence:'Please use the stairs during the drill.' },
  { th:'เสื้อชูชีพอยู่ในตู้เสื้อผ้า',                        sentence:'Your life jacket is in the wardrobe.' },
  { th:'ท่านมีอาการแพ้อาหารไหมคะ',                        sentence:'Do you have any food allergies?' },
  { th:'ขออนุญาตเก็บจานได้ไหมคะ',                          sentence:'May I clear these plates?' },
  { th:'ขอให้อร่อยนะคะ',                                  sentence:'Enjoy your meal.' },
  { th:'เครื่องดื่มนี้รวมในแพ็กเกจของท่านแล้ว',              sentence:'That drink is included in your package.' },
  { th:'ศูนย์การแพทย์อยู่ชั้นสองค่ะ',                       sentence:'The medical centre is on deck two.' },
  { th:'ดิฉันจะกลับมาจัดเตียงตอนเย็น',                      sentence:'I will return this evening for turndown service.' },
  { th:'กรุณาวางกระเป๋าไว้หน้าห้องพัก',                     sentence:'Please leave your suitcases outside your cabin.' },
  { th:'ขอบคุณที่ร่วมเดินทางกับเรานะคะ',                    sentence:'Thank you for sailing with us.' },
  { th:'ขอไปหาคำตอบให้ทันทีนะคะ',                          sentence:'Let me find out for you right away.' },
];

const CRUISE_FILL_DIALOGUES = [
  { id:'embark', title:'Embarkation day', th:'วันขึ้นเรือ', lines:[
    { speaker:'Crew', before:'Good afternoon, and welcome ', after:'. May I see your boarding pass?', options:['aboard','inside','over','along'], correct:'aboard' },
    { speaker:'Guest', before:'Here it is. This is our first cruise.', after:'', fixed:true },
    { speaker:'Crew', before:'Then let me explain a few things. Your ', after:' is on deck nine, midship.', options:['stateroom','gangway','galley','folio'], correct:'stateroom' },
    { speaker:'Guest', before:'Thank you. When will our luggage arrive?', after:'', fixed:true },
    { speaker:'Crew', before:'It will be ', after:' to your cabin within a few hours.', options:['delivered','collected','returned','cancelled'], correct:'delivered' },
    { speaker:'Crew', before:'This afternoon there is a ', after:' drill, which is compulsory for everyone.', options:['muster','tender','crew','fire'], correct:'muster' },
    { speaker:'Guest', before:'Where do we need to go?', after:'', fixed:true },
    { speaker:'Crew', before:'Your muster station is printed on the back of your ', after:' card.', options:['cruise','credit','boarding','comment'], correct:'cruise' },
    { speaker:'Crew', before:'Please take the ', after:', not the lift, when the alarm sounds.', options:['stairs','tender','gangway','trolley'], correct:'stairs' },
    { speaker:'Guest', before:'Understood. Thank you for your help.', after:'', fixed:true },
    { speaker:'Crew', before:'It\u2019s my pleasure. Do ', after:' the rest of your afternoon.', options:['enjoy','avoid','delay','forget'], correct:'enjoy' },
  ]},
  { id:'port', title:'A day in port', th:'วันแวะท่าเรือ', lines:[
    { speaker:'Guest', before:'Excuse me, what time do we have to be back on the ship?', after:'', fixed:true },
    { speaker:'Crew', before:'All ', after:' time is four thirty this afternoon.', options:['aboard','ashore','around','abroad'], correct:'aboard' },
    { speaker:'Crew', before:'Please remember the ship runs on ship\u2019s ', after:', not local time.', options:['time','clock','hour','schedule'], correct:'time' },
    { speaker:'Guest', before:'Good to know. How do we get ashore?', after:'', fixed:true },
    { speaker:'Crew', before:'The ship cannot dock here, so a ', after:' boat will take you across.', options:['tender','life','sail','row'], correct:'tender' },
    { speaker:'Crew', before:'It leaves from the ', after:' every twenty minutes.', options:['gangway','galley','atrium','bridge'], correct:'gangway' },
    { speaker:'Guest', before:'Should we take anything with us?', after:'', fixed:true },
    { speaker:'Crew', before:'Please take your cruise card and some local ', after:'.', options:['currency','language','weather','luggage'], correct:'currency' },
    { speaker:'Crew', before:'If you\u2019d like a guided tour, the shore ', after:' desk is on deck five.', options:['excursion','service','landing','arrival'], correct:'excursion' },
    { speaker:'Guest', before:'Perfect, thank you very much.', after:'', fixed:true },
  ]},
];
