/* Learning pages: source-aligned modules, transparent provenance and self-study progress. */
const LearningHub = (() => {
 const M=LearningModel, D=M.D, E=M.esc;
 const T=(en,th)=>I18N.current==='th'?th:en;
 let course=null, moduleId=null, filter={kind:'both',category:'all',query:'',limit:30};
 function ensure(){if(course!==Courses.currentId){course=Courses.currentId;moduleId=null;filter={kind:'both',category:'all',query:'',limit:30};}}
 function title(m){return T(m.title,m.th);}
 function courseHeader(){return `<div class="lh-course-line"><span class="lh-eyebrow">${E(T(D.courses[course].title,D.courses[course].th))}</span><button class="lh-link" data-lh="switch">${T('Switch course','เปลี่ยนหลักสูตร')} ↗</button></div>`;}
 function stats(){const es=M.items(course);return {words:es.filter(e=>e.kind==='word').length,phrases:es.filter(e=>e.kind==='phrase').length};}
 function sourceNote(){return `<details class="lh-source"><summary>${T('Course sources & details to confirm','เอกสารหลักสูตรและรายละเอียดที่ต้องยืนยัน')}</summary><p>${T('Module titles follow the uploaded outlines. Short lessons, models and module mappings are editorial learning support, not quotations or newly approved course requirements.','ชื่อโมดูลอิงจากโครงร่างที่แนบ บทเรียนสั้น ตัวอย่าง และการจัดหมวดเป็นสื่อเสริมที่เรียบเรียงขึ้น ไม่ใช่ข้อความคัดลอกหรือข้อกำหนดหลักสูตรที่ได้รับอนุมัติใหม่')}</p><p>${E(D.courses[course].duration)}</p><p>${D.courses[course].sources.map(E).join('<br>')}</p><a href="LEARNING_GUIDE.html" target="_blank" rel="noopener">${T('Read the mapping and source notes','อ่านการจัดหมวดและหมายเหตุเอกสาร')} ↗</a></details>`;}
 function overview(){
  const s=stats(),progress=Progress.learningState(),ms=D.modules[course],done=ms.filter(m=>progress.modules[m.id]).length;
  return `${courseHeader()}<div class="lh-hero"><div><div class="lh-eyebrow">${T('LEARN FIRST. PRACTISE WITH PURPOSE.','เรียนรู้ก่อน แล้วฝึกอย่างมีเป้าหมาย')}</div><h2>${T('Your learning path','เส้นทางการเรียนรู้ของคุณ')}</h2><p>${T('Choose a module. Read the short lesson, study the words and phrases, then build your own practice set.','เลือกโมดูล อ่านบทเรียนสั้น เรียนรู้คำศัพท์และวลี แล้วจัดชุดฝึกของคุณเอง')}</p></div><div class="lh-stats"><span><b>${s.words}</b>${T('words','คำศัพท์')}</span><span><b>${s.phrases}</b>${T('phrases','วลี')}</span><span><b>${done}/${ms.length}</b>${T('marked studied','ทำเครื่องหมายว่าเรียนแล้ว')}</span></div></div>
  <p class="lh-caption">${T('Studied is a self-study record, not a passing grade. Shared entries are counted once within a course.','การทำเครื่องหมายว่าเรียนแล้วเป็นบันทึกการเรียนด้วยตนเอง ไม่ใช่ผลสอบผ่าน คำที่ใช้ร่วมกันนับครั้งเดียวภายในหลักสูตร')}</p>
  <div class="lh-module-grid">${ms.map((m,i)=>{
    const es=M.items(course,m.id),w=es.filter(e=>e.kind==='word').length,p=es.length-w,studied=!!progress.modules[m.id];
    return `<article class="lh-module ${studied?'is-studied':''}"><div class="lh-module-top"><span class="lh-index">${m.supplement?'+':m.id==='ca2'?'A2':m.id==='c8'?'08':String(i+1).padStart(2,'0')}</span><span class="lh-badge">${m.supplement?T('Supplement','บทเสริม'):m.teacherAssessed?T('Includes teacher task','มีงานที่ครูประเมิน'):T('Self-study + practice','เรียนรู้และฝึกด้วยตนเอง')}</span></div><h3>${E(title(m))}</h3><p>${E(T(m.goal,m.goalTh))}</p><div class="lh-meta">${w} ${T('words','คำศัพท์')} · ${p} ${T('phrases','วลี')}${studied?' · ✓ '+T('Studied','เรียนแล้ว'):''}</div><button class="btn btn-outline btn-block" data-lh="module" data-id="${m.id}">${T('Open lesson','เปิดบทเรียน')} →</button></article>`;
  }).join('')}</div>${sourceNote()}<section class="lh-panel"><h3>${T('Course assessment ≠ vocabulary practice','การประเมินหลักสูตร ≠ การฝึกคำศัพท์')}</h3><p>${T('The source course also requires teacher-assessed evidence. The practice builder below does not calculate an official course grade.','หลักสูตรในเอกสารยังต้องใช้หลักฐานที่ครูประเมิน ระบบชุดฝึกนี้ไม่คำนวณคะแนนหลักสูตรอย่างเป็นทางการ')}</p><div class="lh-weight-list">${D.courses[course].assessment.map(([name,weight])=>`<div><span>${E(name)}</span><b>${weight}%</b></div>`).join('')}</div></section>`;
 }
 function lesson(){
  const m=D.modules[course].find(m=>m.id===moduleId);if(!m){moduleId=null;return overview();}
  const es=M.items(course,moduleId),state=Progress.learningState();
  let pool=M.items(course,moduleId,filter.kind,filter.category);
  if(filter.query){const q=filter.query.toLowerCase();pool=pool.filter(e=>[e.en,e.th,e.category].some(v=>v.toLowerCase().includes(q)));}
  const cats=M.categories(course,moduleId,filter.kind);
  return `${courseHeader()}<button class="lh-link lh-back" data-lh="back">← ${T('All learning modules','โมดูลการเรียนรู้ทั้งหมด')}</button><header class="lh-lesson-head"><span class="lh-eyebrow">${T('SHORT LESSON','บทเรียนสั้น')}</span><h2>${E(title(m))}</h2><p>${E(T(m.goal,m.goalTh))}</p><div class="lh-actions"><button class="btn btn-gold" data-lh="assess" data-id="${m.id}">${T('Practise this module','ฝึกโมดูลนี้')} →</button><button class="btn btn-outline" data-lh="studied" data-id="${m.id}">${state.modules[m.id]?'✓ '+T('Marked studied — undo','ทำเครื่องหมายว่าเรียนแล้ว — ยกเลิก'):T('Mark lesson studied','ทำเครื่องหมายว่าเรียนบทนี้แล้ว')}</button></div></header>
  <div class="lh-lesson-grid"><section class="lh-panel"><h3>${T('Understand & use','เข้าใจและนำไปใช้')}</h3>${m.points.map(([en,th],i)=>`<div class="lh-point"><b>${i+1}</b><div><p>${E(en)}</p><p lang="th" class="lh-th">${E(th)}</p></div></div>`).join('')}<p class="lh-caption">${T('Newly authored learning support; aligned to the source topic.','สื่อเสริมที่เรียบเรียงขึ้นใหม่ โดยสอดคล้องกับหัวข้อในเอกสาร')}</p></section><section class="lh-panel"><h3>${T('Model exchange','ตัวอย่างการโต้ตอบ')}</h3>${m.model.map(([who,line])=>`<div class="lh-turn"><span>${E(who)}</span><p>${E(line)}</p><button class="lh-link" data-lh-speak="${E(line)}">▷ ${T('Listen','ฟัง')}</button></div>`).join('')}<p class="lh-caption">${T('Fictional training example. Use your real experience and confirm workplace details.','ตัวอย่างสมมติสำหรับฝึก ใช้ประสบการณ์จริงของคุณและยืนยันรายละเอียดของที่ทำงาน')}</p></section></div>
  <section class="lh-panel lh-transfer"><h3>${m.teacherAssessed?T('Teacher / partner task','งานฝึกกับครูหรือคู่ฝึก'):T('Try it at work','ลองใช้ในสถานการณ์งาน')}</h3><p>${E(T(m.task,m.taskTh))}</p>${m.teacherAssessed?`<p class="lh-caption">${T('Human feedback is required for this task; no automatic speaking or CV grade is awarded.','งานนี้ต้องได้รับข้อเสนอแนะจากผู้ประเมิน ไม่มีการให้คะแนนการพูดหรือประวัติย่อโดยอัตโนมัติ')}</p>`:''}</section>
  <section class="lh-library"><h3>${T('Module words & phrases','คำศัพท์และวลีในโมดูล')}</h3><p class="lh-caption">${T('Includes primary content and cross-referenced revision items. An entry appears only once in each practice set.','รวมเนื้อหาหลักและรายการทบทวนที่อ้างอิงข้ามโมดูล แต่ละรายการปรากฏครั้งเดียวในชุดฝึก')}</p><div class="lh-filter-row"><label>${T('Content','เนื้อหา')}<select id="lhKind"><option value="both" ${filter.kind==='both'?'selected':''}>${T('Words & phrases','คำศัพท์และวลี')}</option><option value="word" ${filter.kind==='word'?'selected':''}>${T('Words only','เฉพาะคำศัพท์')}</option><option value="phrase" ${filter.kind==='phrase'?'selected':''}>${T('Phrases only','เฉพาะวลี')}</option></select></label><label>${T('Category','หมวดหมู่')}<select id="lhCategory"><option value="all">${T('All categories','ทุกหมวดหมู่')}</option>${cats.map(c=>`<option value="${E(c.id)}" ${filter.category===c.id?'selected':''}>${E(T(c.en,c.th))}</option>`).join('')}</select></label><label>${T('Find an entry','ค้นหารายการ')}<input id="lhQuery" value="${E(filter.query)}" placeholder="${T('English or Thai','ภาษาอังกฤษหรือภาษาไทย')}"></label></div><p class="lh-caption">${pool.length} ${T('matching entries','รายการที่ตรงเงื่อนไข')} · ${es.filter(e=>state.items[e.id]).length}/${es.length} ${T('marked reviewed','ทำเครื่องหมายว่าทบทวนแล้ว')}</p><div class="lh-entry-grid">${pool.slice(0,filter.limit).map(e=>entryCard(e,state)).join('')||`<p class="lh-empty">${T('No entries match these filters.','ไม่พบรายการที่ตรงกับตัวกรอง')}</p>`}</div>${pool.length>filter.limit?`<button class="btn btn-outline btn-block" data-lh="more">${T('Show 30 more','แสดงเพิ่ม 30 รายการ')}</button>`:''}</section><p class="lh-caption">${T('Source topic','หัวข้ออ้างอิง')}: ${E(m.source)}</p>${sourceNote()}`;
 }
 function entryCard(e,state){
  const reviewed=!!state.items[e.id],primary=D.modules[course].find(m=>m.id===e.mapping.primary);
  return `<article class="lh-entry"><div class="lh-entry-top"><span class="lh-badge">${T(e.kind==='word'?'Word':'Phrase',e.kind==='word'?'คำศัพท์':'วลี')}</span><button class="lh-link" data-lh-speak="${E(e.en)}" aria-label="${E(T('Listen to ','ฟัง ')+e.en)}">▷ ${T('Listen','ฟัง')}</button></div><h4>${E(e.en)}</h4><p lang="th" class="lh-meaning">${E(e.th)}</p><details><summary>${T('Meaning, example & module','ความหมาย ตัวอย่าง และโมดูล')}</summary><p>${E(e.description)}</p>${e.descriptionTh?`<p class="lh-th" lang="th">${E(e.descriptionTh)}</p>`:''}${e.example?`<blockquote>${E(e.example)}<span class="lh-th" lang="th">${E(e.exampleTh)}</span></blockquote>`:''}<p class="lh-caption">${E(T(e.category,e.categoryTh))}<br>${T('Primary module','โมดูลหลัก')}: ${E(title(primary))}<br>${T('Origin','ที่มา')}: ${E(e.origin)}</p></details><button class="lh-review-btn ${reviewed?'reviewed':''}" data-lh="reviewed" data-id="${E(e.id)}" aria-pressed="${reviewed}">${reviewed?'✓ '+T('Reviewed — undo','ทบทวนแล้ว — ยกเลิก'):T('Mark reviewed','ทำเครื่องหมายว่าทบทวนแล้ว')}</button></article>`;
 }
 function render(){ensure();const el=document.getElementById('learningRoot');if(el)el.innerHTML=moduleId?lesson():overview();}
 function open(id=null){ensure();moduleId=id;filter={kind:'both',category:'all',query:'',limit:30};Nav.go('learning');}
 function home(){const el=document.getElementById('learningHomeCard');if(el)el.innerHTML=`<span class="lh-eyebrow">${T('YOUR COURSE, ORGANISED','จัดการเรียนรู้ตามหลักสูตร')}</span><h3>${T('Learn by module','เรียนรู้ตามโมดูล')}</h3><p>${T('Short lessons → useful words & phrases → your own assessment.','บทเรียนสั้น → คำศัพท์และวลีที่ใช้ได้จริง → แบบฝึกที่คุณเลือก')}</p><button class="btn btn-gold" onclick="LearningHub.open()">${T('Open Learning','เปิดส่วนการเรียนรู้')} →</button>`;}
 function init(){
  document.addEventListener('click',e=>{
   const speech=e.target.closest('[data-lh-speak]');if(speech){Speech.speak(speech.dataset.lhSpeak,{rate:App.speechRate()});return;}
   const b=e.target.closest('[data-lh]');if(!b)return;
   if(b.dataset.lh==='module')open(b.dataset.id);
   if(b.dataset.lh==='back')open();
   if(b.dataset.lh==='switch')App.showCourseChooser({cancellable:true});
   if(b.dataset.lh==='assess')AssessmentBuilder.open(b.dataset.id);
   if(b.dataset.lh==='studied'){Progress.setLearningModule(b.dataset.id,!Progress.learningState().modules[b.dataset.id]);App.refreshHome();render();}
   if(b.dataset.lh==='reviewed'){Progress.setLearningItem(b.dataset.id,!Progress.learningState().items[b.dataset.id]);const sy=window.scrollY;render();window.scrollTo(0,sy);}
   if(b.dataset.lh==='more'){filter.limit+=30;const sy=window.scrollY;render();window.scrollTo(0,sy);}
  });
  document.addEventListener('change',e=>{if(e.target.id==='lhKind'){filter.kind=e.target.value;filter.category='all';filter.limit=30;render();}if(e.target.id==='lhCategory'){filter.category=e.target.value;filter.limit=30;render();}});
  let searchTimer;document.addEventListener('input',e=>{if(e.target.id!=='lhQuery')return;filter.query=e.target.value;clearTimeout(searchTimer);searchTimer=setTimeout(()=>{const pos=e.target.selectionStart,sy=window.scrollY;render();const input=document.getElementById('lhQuery');input.focus({preventScroll:true});input.setSelectionRange(pos,pos);window.scrollTo(0,sy);},200);});
 }
 return {render,open,home,init};
})();
